package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CamposParametrizables generated by Zathura powered by
 * Hibernate-tools(hbm2java)
 */
public class CamposParametrizables implements java.io.Serializable {

	private Long idCapa;
	private Tabla tabla;
	private String nombre;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;
	private Set<SolicitudCampo> solicitudCampos = new HashSet<SolicitudCampo>(0);

	public CamposParametrizables() {
	}

	public CamposParametrizables(Long idCapa, Tabla tabla, String nombre,
			Date fechaCreacion, String operCreador, Date fechaModificacion,
			String operModifica, String estadoRegistro) {
		this.idCapa = idCapa;
		this.tabla = tabla;
		this.nombre = nombre;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public CamposParametrizables(Long idCapa, Tabla tabla, String nombre,
			Date fechaCreacion, String operCreador, Date fechaModificacion,
			String operModifica, String estadoRegistro,
			Set<SolicitudCampo> solicitudCampos) {
		this.idCapa = idCapa;
		this.tabla = tabla;
		this.nombre = nombre;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
		this.solicitudCampos = solicitudCampos;
	}

	public Long getIdCapa() {
		return this.idCapa;
	}

	public void setIdCapa(Long idCapa) {
		this.idCapa = idCapa;
	}

	public Tabla getTabla() {
		return this.tabla;
	}

	public void setTabla(Tabla tabla) {
		this.tabla = tabla;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

	public Set<SolicitudCampo> getSolicitudCampos() {
		return this.solicitudCampos;
	}

	public void setSolicitudCampos(Set<SolicitudCampo> solicitudCampos) {
		this.solicitudCampos = solicitudCampos;
	}

}
