package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * ClavesParaRotar generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class ClavesParaRotar implements java.io.Serializable {

	private Long idClpr;
	private ClaveFabricacion claveFabricacion;
	private Sucursal sucursal;
	private Long ano;
	private Long mes;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;

	public ClavesParaRotar() {
	}

	public ClavesParaRotar(Long idClpr, ClaveFabricacion claveFabricacion,
			Date fechaCreacion, String operCreador, Date fechaModificacion,
			String operModifica, String estadoRegistro) {
		this.idClpr = idClpr;
		this.claveFabricacion = claveFabricacion;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public ClavesParaRotar(Long idClpr, ClaveFabricacion claveFabricacion,
			Sucursal sucursal, Long ano, Long mes, Date fechaCreacion,
			String operCreador, Date fechaModificacion, String operModifica,
			String estadoRegistro) {
		this.idClpr = idClpr;
		this.claveFabricacion = claveFabricacion;
		this.sucursal = sucursal;
		this.ano = ano;
		this.mes = mes;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public Long getIdClpr() {
		return this.idClpr;
	}

	public void setIdClpr(Long idClpr) {
		this.idClpr = idClpr;
	}

	public ClaveFabricacion getClaveFabricacion() {
		return this.claveFabricacion;
	}

	public void setClaveFabricacion(ClaveFabricacion claveFabricacion) {
		this.claveFabricacion = claveFabricacion;
	}

	public Sucursal getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Sucursal sucursal) {
		this.sucursal = sucursal;
	}

	public Long getAno() {
		return this.ano;
	}

	public void setAno(Long ano) {
		this.ano = ano;
	}

	public Long getMes() {
		return this.mes;
	}

	public void setMes(Long mes) {
		this.mes = mes;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

}
