package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * Contacto generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class Contacto implements java.io.Serializable {

	private Long idCont;
	private TipoContacto tipoContacto;
	private AtencionVendedor atencionVendedor;
	private Sucursal sucursal;
	private String nombreCompleto;
	private String telefono1;
	private String telefono2;
	private String email;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;

	public Contacto() {
	}

	public Contacto(Long idCont, TipoContacto tipoContacto,
			String nombreCompleto, Date fechaCreacion, String operCreador,
			Date fechaModificacion, String operModifica, String estadoRegistro) {
		this.idCont = idCont;
		this.tipoContacto = tipoContacto;
		this.nombreCompleto = nombreCompleto;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public Contacto(Long idCont, TipoContacto tipoContacto,
			AtencionVendedor atencionVendedor, Sucursal sucursal,
			String nombreCompleto, String telefono1, String telefono2,
			String email, Date fechaCreacion, String operCreador,
			Date fechaModificacion, String operModifica, String estadoRegistro) {
		this.idCont = idCont;
		this.tipoContacto = tipoContacto;
		this.atencionVendedor = atencionVendedor;
		this.sucursal = sucursal;
		this.nombreCompleto = nombreCompleto;
		this.telefono1 = telefono1;
		this.telefono2 = telefono2;
		this.email = email;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public Long getIdCont() {
		return this.idCont;
	}

	public void setIdCont(Long idCont) {
		this.idCont = idCont;
	}

	public TipoContacto getTipoContacto() {
		return this.tipoContacto;
	}

	public void setTipoContacto(TipoContacto tipoContacto) {
		this.tipoContacto = tipoContacto;
	}

	public AtencionVendedor getAtencionVendedor() {
		return this.atencionVendedor;
	}

	public void setAtencionVendedor(AtencionVendedor atencionVendedor) {
		this.atencionVendedor = atencionVendedor;
	}

	public Sucursal getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Sucursal sucursal) {
		this.sucursal = sucursal;
	}

	public String getNombreCompleto() {
		return this.nombreCompleto;
	}

	public void setNombreCompleto(String nombreCompleto) {
		this.nombreCompleto = nombreCompleto;
	}

	public String getTelefono1() {
		return this.telefono1;
	}

	public void setTelefono1(String telefono1) {
		this.telefono1 = telefono1;
	}

	public String getTelefono2() {
		return this.telefono2;
	}

	public void setTelefono2(String telefono2) {
		this.telefono2 = telefono2;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

}
