package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * DescuentoComercial generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class DescuentoComercial implements java.io.Serializable {

	private Long idDeco;
	private Persona persona;
	private Grupo grupo;
	private Empresa empresa;
	private Sucursal sucursalBySucursal;
	private Sucursal sucursalByIdSucu;
	private Date fechaInicial;
	private Date fechaFinal;
	private String espacios;
	private Long estadoPlano;
	private Long creadoAutomatico;
	private Long todasSucursales;
	private Long tipoAsocGrupoItem;
	private String asocGrupoItem;
	private Double porcDescMinItem;
	private Double porcDescItem;
	private Double porcDescMaxItem;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;

	public DescuentoComercial() {
	}

	public DescuentoComercial(Long idDeco, Grupo grupo,
			Sucursal sucursalBySucursal, Date fechaInicial, Date fechaFinal,
			Date fechaCreacion, String operCreador, Date fechaModificacion,
			String operModifica, String estadoRegistro) {
		this.idDeco = idDeco;
		this.grupo = grupo;
		this.sucursalBySucursal = sucursalBySucursal;
		this.fechaInicial = fechaInicial;
		this.fechaFinal = fechaFinal;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public DescuentoComercial(Long idDeco, Persona persona, Grupo grupo,
			Empresa empresa, Sucursal sucursalBySucursal,
			Sucursal sucursalByIdSucu, Date fechaInicial, Date fechaFinal,
			String espacios, Long estadoPlano, Long creadoAutomatico,
			Long todasSucursales, Long tipoAsocGrupoItem, String asocGrupoItem,
			Double porcDescMinItem, Double porcDescItem,
			Double porcDescMaxItem, Date fechaCreacion, String operCreador,
			Date fechaModificacion, String operModifica, String estadoRegistro) {
		this.idDeco = idDeco;
		this.persona = persona;
		this.grupo = grupo;
		this.empresa = empresa;
		this.sucursalBySucursal = sucursalBySucursal;
		this.sucursalByIdSucu = sucursalByIdSucu;
		this.fechaInicial = fechaInicial;
		this.fechaFinal = fechaFinal;
		this.espacios = espacios;
		this.estadoPlano = estadoPlano;
		this.creadoAutomatico = creadoAutomatico;
		this.todasSucursales = todasSucursales;
		this.tipoAsocGrupoItem = tipoAsocGrupoItem;
		this.asocGrupoItem = asocGrupoItem;
		this.porcDescMinItem = porcDescMinItem;
		this.porcDescItem = porcDescItem;
		this.porcDescMaxItem = porcDescMaxItem;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public Long getIdDeco() {
		return this.idDeco;
	}

	public void setIdDeco(Long idDeco) {
		this.idDeco = idDeco;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public Grupo getGrupo() {
		return this.grupo;
	}

	public void setGrupo(Grupo grupo) {
		this.grupo = grupo;
	}

	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	public Sucursal getSucursalBySucursal() {
		return this.sucursalBySucursal;
	}

	public void setSucursalBySucursal(Sucursal sucursalBySucursal) {
		this.sucursalBySucursal = sucursalBySucursal;
	}

	public Sucursal getSucursalByIdSucu() {
		return this.sucursalByIdSucu;
	}

	public void setSucursalByIdSucu(Sucursal sucursalByIdSucu) {
		this.sucursalByIdSucu = sucursalByIdSucu;
	}

	public Date getFechaInicial() {
		return this.fechaInicial;
	}

	public void setFechaInicial(Date fechaInicial) {
		this.fechaInicial = fechaInicial;
	}

	public Date getFechaFinal() {
		return this.fechaFinal;
	}

	public void setFechaFinal(Date fechaFinal) {
		this.fechaFinal = fechaFinal;
	}

	public String getEspacios() {
		return this.espacios;
	}

	public void setEspacios(String espacios) {
		this.espacios = espacios;
	}

	public Long getEstadoPlano() {
		return this.estadoPlano;
	}

	public void setEstadoPlano(Long estadoPlano) {
		this.estadoPlano = estadoPlano;
	}

	public Long getCreadoAutomatico() {
		return this.creadoAutomatico;
	}

	public void setCreadoAutomatico(Long creadoAutomatico) {
		this.creadoAutomatico = creadoAutomatico;
	}

	public Long getTodasSucursales() {
		return this.todasSucursales;
	}

	public void setTodasSucursales(Long todasSucursales) {
		this.todasSucursales = todasSucursales;
	}

	public Long getTipoAsocGrupoItem() {
		return this.tipoAsocGrupoItem;
	}

	public void setTipoAsocGrupoItem(Long tipoAsocGrupoItem) {
		this.tipoAsocGrupoItem = tipoAsocGrupoItem;
	}

	public String getAsocGrupoItem() {
		return this.asocGrupoItem;
	}

	public void setAsocGrupoItem(String asocGrupoItem) {
		this.asocGrupoItem = asocGrupoItem;
	}

	public Double getPorcDescMinItem() {
		return this.porcDescMinItem;
	}

	public void setPorcDescMinItem(Double porcDescMinItem) {
		this.porcDescMinItem = porcDescMinItem;
	}

	public Double getPorcDescItem() {
		return this.porcDescItem;
	}

	public void setPorcDescItem(Double porcDescItem) {
		this.porcDescItem = porcDescItem;
	}

	public Double getPorcDescMaxItem() {
		return this.porcDescMaxItem;
	}

	public void setPorcDescMaxItem(Double porcDescMaxItem) {
		this.porcDescMaxItem = porcDescMaxItem;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

}
