package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class Empresa implements java.io.Serializable {

	private Long idEmpr;
	private Persona persona;
	private DivisionPolitica divisionPolitica;
	private TipoIdentificacion tipoIdentificacion;
	private String nombre;
	private Long identificacion;
	private String telefono1;
	private String telefono2;
	private String direccion;
	private String apartadoAereo;
	private String email;
	private String fax;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;
	private Set<Proveedor> proveedors = new HashSet<Proveedor>(0);
	private Set<Sucursal> sucursals = new HashSet<Sucursal>(0);
	private Set<OrdenesDeCompra> ordenesDeCompras = new HashSet<OrdenesDeCompra>(
			0);
	private Set<Compania> companias = new HashSet<Compania>(0);
	private Set<RelacionComercial> relacionComercials = new HashSet<RelacionComercial>(
			0);
	private Set<DescuentoComercial> descuentoComercials = new HashSet<DescuentoComercial>(
			0);
	private Set<Cliente> clientes = new HashSet<Cliente>(0);
	private Set<ListaPreciosEspeciales> listaPreciosEspecialeses = new HashSet<ListaPreciosEspeciales>(
			0);

	public Empresa() {
	}

	public Empresa(Long idEmpr, TipoIdentificacion tipoIdentificacion,
			String nombre, Long identificacion, Date fechaCreacion,
			String operCreador, Date fechaModificacion, String operModifica,
			String estadoRegistro) {
		this.idEmpr = idEmpr;
		this.tipoIdentificacion = tipoIdentificacion;
		this.nombre = nombre;
		this.identificacion = identificacion;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public Empresa(Long idEmpr, Persona persona,
			DivisionPolitica divisionPolitica,
			TipoIdentificacion tipoIdentificacion, String nombre,
			Long identificacion, String telefono1, String telefono2,
			String direccion, String apartadoAereo, String email, String fax,
			Date fechaCreacion, String operCreador, Date fechaModificacion,
			String operModifica, String estadoRegistro,
			Set<Proveedor> proveedors, Set<Sucursal> sucursals,
			Set<OrdenesDeCompra> ordenesDeCompras, Set<Compania> companias,
			Set<RelacionComercial> relacionComercials,
			Set<DescuentoComercial> descuentoComercials, Set<Cliente> clientes,
			Set<ListaPreciosEspeciales> listaPreciosEspecialeses) {
		this.idEmpr = idEmpr;
		this.persona = persona;
		this.divisionPolitica = divisionPolitica;
		this.tipoIdentificacion = tipoIdentificacion;
		this.nombre = nombre;
		this.identificacion = identificacion;
		this.telefono1 = telefono1;
		this.telefono2 = telefono2;
		this.direccion = direccion;
		this.apartadoAereo = apartadoAereo;
		this.email = email;
		this.fax = fax;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
		this.proveedors = proveedors;
		this.sucursals = sucursals;
		this.ordenesDeCompras = ordenesDeCompras;
		this.companias = companias;
		this.relacionComercials = relacionComercials;
		this.descuentoComercials = descuentoComercials;
		this.clientes = clientes;
		this.listaPreciosEspecialeses = listaPreciosEspecialeses;
	}

	public Long getIdEmpr() {
		return this.idEmpr;
	}

	public void setIdEmpr(Long idEmpr) {
		this.idEmpr = idEmpr;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public DivisionPolitica getDivisionPolitica() {
		return this.divisionPolitica;
	}

	public void setDivisionPolitica(DivisionPolitica divisionPolitica) {
		this.divisionPolitica = divisionPolitica;
	}

	public TipoIdentificacion getTipoIdentificacion() {
		return this.tipoIdentificacion;
	}

	public void setTipoIdentificacion(TipoIdentificacion tipoIdentificacion) {
		this.tipoIdentificacion = tipoIdentificacion;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Long getIdentificacion() {
		return this.identificacion;
	}

	public void setIdentificacion(Long identificacion) {
		this.identificacion = identificacion;
	}

	public String getTelefono1() {
		return this.telefono1;
	}

	public void setTelefono1(String telefono1) {
		this.telefono1 = telefono1;
	}

	public String getTelefono2() {
		return this.telefono2;
	}

	public void setTelefono2(String telefono2) {
		this.telefono2 = telefono2;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getApartadoAereo() {
		return this.apartadoAereo;
	}

	public void setApartadoAereo(String apartadoAereo) {
		this.apartadoAereo = apartadoAereo;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

	public Set<Proveedor> getProveedors() {
		return this.proveedors;
	}

	public void setProveedors(Set<Proveedor> proveedors) {
		this.proveedors = proveedors;
	}

	public Set<Sucursal> getSucursals() {
		return this.sucursals;
	}

	public void setSucursals(Set<Sucursal> sucursals) {
		this.sucursals = sucursals;
	}

	public Set<OrdenesDeCompra> getOrdenesDeCompras() {
		return this.ordenesDeCompras;
	}

	public void setOrdenesDeCompras(Set<OrdenesDeCompra> ordenesDeCompras) {
		this.ordenesDeCompras = ordenesDeCompras;
	}

	public Set<Compania> getCompanias() {
		return this.companias;
	}

	public void setCompanias(Set<Compania> companias) {
		this.companias = companias;
	}

	public Set<RelacionComercial> getRelacionComercials() {
		return this.relacionComercials;
	}

	public void setRelacionComercials(Set<RelacionComercial> relacionComercials) {
		this.relacionComercials = relacionComercials;
	}

	public Set<DescuentoComercial> getDescuentoComercials() {
		return this.descuentoComercials;
	}

	public void setDescuentoComercials(
			Set<DescuentoComercial> descuentoComercials) {
		this.descuentoComercials = descuentoComercials;
	}

	public Set<Cliente> getClientes() {
		return this.clientes;
	}

	public void setClientes(Set<Cliente> clientes) {
		this.clientes = clientes;
	}

	public Set<ListaPreciosEspeciales> getListaPreciosEspecialeses() {
		return this.listaPreciosEspecialeses;
	}

	public void setListaPreciosEspecialeses(
			Set<ListaPreciosEspeciales> listaPreciosEspecialeses) {
		this.listaPreciosEspecialeses = listaPreciosEspecialeses;
	}

}
