package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * Garantia generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class Garantia implements java.io.Serializable {

	private Long idGar;
	private Fallas fallas;
	private TipoGarantia tipoGarantia;
	private Documento documento;
	private Bateriologo bateriologo;
	private Referencia referencia;
	private ClaveFabricacion claveFabricacion;
	private Date fechaVenta;
	private Date fechaCambio;
	private String numeroGarantia;
	private String alineacionTrazabilidad;
	private String placaTrazabilidad;
	private Long diaTrazabilidad;
	private String mesTrazabilidad;
	private Long anoTrazabilidad;
	private String lineaTrazabilidad;
	private String turnoTrazabilidad;
	private String estado;
	private String observacion;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;

	public Garantia() {
	}

	public Garantia(Long idGar, TipoGarantia tipoGarantia, Documento documento,
			Referencia referencia, ClaveFabricacion claveFabricacion,
			Date fechaCreacion, String operCreador, Date fechaModificacion,
			String operModifica, String estadoRegistro) {
		this.idGar = idGar;
		this.tipoGarantia = tipoGarantia;
		this.documento = documento;
		this.referencia = referencia;
		this.claveFabricacion = claveFabricacion;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public Garantia(Long idGar, Fallas fallas, TipoGarantia tipoGarantia,
			Documento documento, Bateriologo bateriologo,
			Referencia referencia, ClaveFabricacion claveFabricacion,
			Date fechaVenta, Date fechaCambio, String numeroGarantia,
			String alineacionTrazabilidad, String placaTrazabilidad,
			Long diaTrazabilidad, String mesTrazabilidad, Long anoTrazabilidad,
			String lineaTrazabilidad, String turnoTrazabilidad, String estado,
			String observacion, Date fechaCreacion, String operCreador,
			Date fechaModificacion, String operModifica, String estadoRegistro) {
		this.idGar = idGar;
		this.fallas = fallas;
		this.tipoGarantia = tipoGarantia;
		this.documento = documento;
		this.bateriologo = bateriologo;
		this.referencia = referencia;
		this.claveFabricacion = claveFabricacion;
		this.fechaVenta = fechaVenta;
		this.fechaCambio = fechaCambio;
		this.numeroGarantia = numeroGarantia;
		this.alineacionTrazabilidad = alineacionTrazabilidad;
		this.placaTrazabilidad = placaTrazabilidad;
		this.diaTrazabilidad = diaTrazabilidad;
		this.mesTrazabilidad = mesTrazabilidad;
		this.anoTrazabilidad = anoTrazabilidad;
		this.lineaTrazabilidad = lineaTrazabilidad;
		this.turnoTrazabilidad = turnoTrazabilidad;
		this.estado = estado;
		this.observacion = observacion;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public Long getIdGar() {
		return this.idGar;
	}

	public void setIdGar(Long idGar) {
		this.idGar = idGar;
	}

	public Fallas getFallas() {
		return this.fallas;
	}

	public void setFallas(Fallas fallas) {
		this.fallas = fallas;
	}

	public TipoGarantia getTipoGarantia() {
		return this.tipoGarantia;
	}

	public void setTipoGarantia(TipoGarantia tipoGarantia) {
		this.tipoGarantia = tipoGarantia;
	}

	public Documento getDocumento() {
		return this.documento;
	}

	public void setDocumento(Documento documento) {
		this.documento = documento;
	}

	public Bateriologo getBateriologo() {
		return this.bateriologo;
	}

	public void setBateriologo(Bateriologo bateriologo) {
		this.bateriologo = bateriologo;
	}

	public Referencia getReferencia() {
		return this.referencia;
	}

	public void setReferencia(Referencia referencia) {
		this.referencia = referencia;
	}

	public ClaveFabricacion getClaveFabricacion() {
		return this.claveFabricacion;
	}

	public void setClaveFabricacion(ClaveFabricacion claveFabricacion) {
		this.claveFabricacion = claveFabricacion;
	}

	public Date getFechaVenta() {
		return this.fechaVenta;
	}

	public void setFechaVenta(Date fechaVenta) {
		this.fechaVenta = fechaVenta;
	}

	public Date getFechaCambio() {
		return this.fechaCambio;
	}

	public void setFechaCambio(Date fechaCambio) {
		this.fechaCambio = fechaCambio;
	}

	public String getNumeroGarantia() {
		return this.numeroGarantia;
	}

	public void setNumeroGarantia(String numeroGarantia) {
		this.numeroGarantia = numeroGarantia;
	}

	public String getAlineacionTrazabilidad() {
		return this.alineacionTrazabilidad;
	}

	public void setAlineacionTrazabilidad(String alineacionTrazabilidad) {
		this.alineacionTrazabilidad = alineacionTrazabilidad;
	}

	public String getPlacaTrazabilidad() {
		return this.placaTrazabilidad;
	}

	public void setPlacaTrazabilidad(String placaTrazabilidad) {
		this.placaTrazabilidad = placaTrazabilidad;
	}

	public Long getDiaTrazabilidad() {
		return this.diaTrazabilidad;
	}

	public void setDiaTrazabilidad(Long diaTrazabilidad) {
		this.diaTrazabilidad = diaTrazabilidad;
	}

	public String getMesTrazabilidad() {
		return this.mesTrazabilidad;
	}

	public void setMesTrazabilidad(String mesTrazabilidad) {
		this.mesTrazabilidad = mesTrazabilidad;
	}

	public Long getAnoTrazabilidad() {
		return this.anoTrazabilidad;
	}

	public void setAnoTrazabilidad(Long anoTrazabilidad) {
		this.anoTrazabilidad = anoTrazabilidad;
	}

	public String getLineaTrazabilidad() {
		return this.lineaTrazabilidad;
	}

	public void setLineaTrazabilidad(String lineaTrazabilidad) {
		this.lineaTrazabilidad = lineaTrazabilidad;
	}

	public String getTurnoTrazabilidad() {
		return this.turnoTrazabilidad;
	}

	public void setTurnoTrazabilidad(String turnoTrazabilidad) {
		this.turnoTrazabilidad = turnoTrazabilidad;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

}
