package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Grupo generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class Grupo implements java.io.Serializable {

	private Long idGrpo;
	private Familia familia;
	private Grupo grupo;
	private String grupo_1;
	private String nombre;
	private Double margenMinimoBodega;
	private Double margenMinimoEnergiteca;
	private String division;
	private String tipoNivel;
	private String especial;
	private String modificaReferencia;
	private String pideGalones;
	private String manejaOrdenCompra;
	private String sugeridoPedido;
	private String asociado;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;
	private Set<Grupo> grupos = new HashSet<Grupo>(0);
	private Set<DescuentoComercial> descuentoComercials = new HashSet<DescuentoComercial>(
			0);
	private Set<DescuentoFinanciero> descuentoFinancieros = new HashSet<DescuentoFinanciero>(
			0);
	private Set<Cartera> carteras = new HashSet<Cartera>(0);
	private Set<GrupoReferencia> grupoReferencias = new HashSet<GrupoReferencia>(
			0);
	private Set<PeriodoGarantia> periodoGarantias = new HashSet<PeriodoGarantia>(
			0);

	public Grupo() {
	}

	public Grupo(Long idGrpo, String grupo_1, Date fechaCreacion,
			String operCreador, Date fechaModificacion, String operModifica,
			String estadoRegistro) {
		this.idGrpo = idGrpo;
		this.grupo_1 = grupo_1;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public Grupo(Long idGrpo, Familia familia, Grupo grupo, String grupo_1,
			String nombre, Double margenMinimoBodega,
			Double margenMinimoEnergiteca, String division, String tipoNivel,
			String especial, String modificaReferencia, String pideGalones,
			String manejaOrdenCompra, String sugeridoPedido, String asociado,
			Date fechaCreacion, String operCreador, Date fechaModificacion,
			String operModifica, String estadoRegistro, Set<Grupo> grupos,
			Set<DescuentoComercial> descuentoComercials,
			Set<DescuentoFinanciero> descuentoFinancieros,
			Set<Cartera> carteras, Set<GrupoReferencia> grupoReferencias,
			Set<PeriodoGarantia> periodoGarantias) {
		this.idGrpo = idGrpo;
		this.familia = familia;
		this.grupo = grupo;
		this.grupo_1 = grupo_1;
		this.nombre = nombre;
		this.margenMinimoBodega = margenMinimoBodega;
		this.margenMinimoEnergiteca = margenMinimoEnergiteca;
		this.division = division;
		this.tipoNivel = tipoNivel;
		this.especial = especial;
		this.modificaReferencia = modificaReferencia;
		this.pideGalones = pideGalones;
		this.manejaOrdenCompra = manejaOrdenCompra;
		this.sugeridoPedido = sugeridoPedido;
		this.asociado = asociado;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
		this.grupos = grupos;
		this.descuentoComercials = descuentoComercials;
		this.descuentoFinancieros = descuentoFinancieros;
		this.carteras = carteras;
		this.grupoReferencias = grupoReferencias;
		this.periodoGarantias = periodoGarantias;
	}

	public Long getIdGrpo() {
		return this.idGrpo;
	}

	public void setIdGrpo(Long idGrpo) {
		this.idGrpo = idGrpo;
	}

	public Familia getFamilia() {
		return this.familia;
	}

	public void setFamilia(Familia familia) {
		this.familia = familia;
	}

	public Grupo getGrupo() {
		return this.grupo;
	}

	public void setGrupo(Grupo grupo) {
		this.grupo = grupo;
	}

	public String getGrupo_1() {
		return this.grupo_1;
	}

	public void setGrupo_1(String grupo_1) {
		this.grupo_1 = grupo_1;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Double getMargenMinimoBodega() {
		return this.margenMinimoBodega;
	}

	public void setMargenMinimoBodega(Double margenMinimoBodega) {
		this.margenMinimoBodega = margenMinimoBodega;
	}

	public Double getMargenMinimoEnergiteca() {
		return this.margenMinimoEnergiteca;
	}

	public void setMargenMinimoEnergiteca(Double margenMinimoEnergiteca) {
		this.margenMinimoEnergiteca = margenMinimoEnergiteca;
	}

	public String getDivision() {
		return this.division;
	}

	public void setDivision(String division) {
		this.division = division;
	}

	public String getTipoNivel() {
		return this.tipoNivel;
	}

	public void setTipoNivel(String tipoNivel) {
		this.tipoNivel = tipoNivel;
	}

	public String getEspecial() {
		return this.especial;
	}

	public void setEspecial(String especial) {
		this.especial = especial;
	}

	public String getModificaReferencia() {
		return this.modificaReferencia;
	}

	public void setModificaReferencia(String modificaReferencia) {
		this.modificaReferencia = modificaReferencia;
	}

	public String getPideGalones() {
		return this.pideGalones;
	}

	public void setPideGalones(String pideGalones) {
		this.pideGalones = pideGalones;
	}

	public String getManejaOrdenCompra() {
		return this.manejaOrdenCompra;
	}

	public void setManejaOrdenCompra(String manejaOrdenCompra) {
		this.manejaOrdenCompra = manejaOrdenCompra;
	}

	public String getSugeridoPedido() {
		return this.sugeridoPedido;
	}

	public void setSugeridoPedido(String sugeridoPedido) {
		this.sugeridoPedido = sugeridoPedido;
	}

	public String getAsociado() {
		return this.asociado;
	}

	public void setAsociado(String asociado) {
		this.asociado = asociado;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

	public Set<Grupo> getGrupos() {
		return this.grupos;
	}

	public void setGrupos(Set<Grupo> grupos) {
		this.grupos = grupos;
	}

	public Set<DescuentoComercial> getDescuentoComercials() {
		return this.descuentoComercials;
	}

	public void setDescuentoComercials(
			Set<DescuentoComercial> descuentoComercials) {
		this.descuentoComercials = descuentoComercials;
	}

	public Set<DescuentoFinanciero> getDescuentoFinancieros() {
		return this.descuentoFinancieros;
	}

	public void setDescuentoFinancieros(
			Set<DescuentoFinanciero> descuentoFinancieros) {
		this.descuentoFinancieros = descuentoFinancieros;
	}

	public Set<Cartera> getCarteras() {
		return this.carteras;
	}

	public void setCarteras(Set<Cartera> carteras) {
		this.carteras = carteras;
	}

	public Set<GrupoReferencia> getGrupoReferencias() {
		return this.grupoReferencias;
	}

	public void setGrupoReferencias(Set<GrupoReferencia> grupoReferencias) {
		this.grupoReferencias = grupoReferencias;
	}

	public Set<PeriodoGarantia> getPeriodoGarantias() {
		return this.periodoGarantias;
	}

	public void setPeriodoGarantias(Set<PeriodoGarantia> periodoGarantias) {
		this.periodoGarantias = periodoGarantias;
	}

}
