package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MovimientoInventario generated by Zathura powered by
 * Hibernate-tools(hbm2java)
 */
public class MovimientoInventario implements java.io.Serializable {

	private Long idMoin;
	private Documento documento;
	private Sucursal sucursalBySucursalRecibeEnvia;
	private Causal causal;
	private Sucursal sucursalBySucursalEntrega;
	private ReferenciaSucursal referenciaSucursal;
	private Long numeroRegistro;
	private Date fechaMovimiento;
	private Double cantidad;
	private String referencia;
	private Double valorTotal;
	private Double porcentajeIva;
	private Double costoUnitario;
	private String placaVehiculo;
	private String claseVenta;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;
	private Set<MovimientoVendedor> movimientoVendedors = new HashSet<MovimientoVendedor>(
			0);

	public MovimientoInventario() {
	}

	public MovimientoInventario(Long idMoin, Documento documento,
			ReferenciaSucursal referenciaSucursal, Long numeroRegistro,
			String referencia, Double valorTotal, Date fechaCreacion,
			String operCreador, Date fechaModificacion, String operModifica,
			String estadoRegistro) {
		this.idMoin = idMoin;
		this.documento = documento;
		this.referenciaSucursal = referenciaSucursal;
		this.numeroRegistro = numeroRegistro;
		this.referencia = referencia;
		this.valorTotal = valorTotal;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public MovimientoInventario(Long idMoin, Documento documento,
			Sucursal sucursalBySucursalRecibeEnvia, Causal causal,
			Sucursal sucursalBySucursalEntrega,
			ReferenciaSucursal referenciaSucursal, Long numeroRegistro,
			Date fechaMovimiento, Double cantidad, String referencia,
			Double valorTotal, Double porcentajeIva, Double costoUnitario,
			String placaVehiculo, String claseVenta, Date fechaCreacion,
			String operCreador, Date fechaModificacion, String operModifica,
			String estadoRegistro, Set<MovimientoVendedor> movimientoVendedors) {
		this.idMoin = idMoin;
		this.documento = documento;
		this.sucursalBySucursalRecibeEnvia = sucursalBySucursalRecibeEnvia;
		this.causal = causal;
		this.sucursalBySucursalEntrega = sucursalBySucursalEntrega;
		this.referenciaSucursal = referenciaSucursal;
		this.numeroRegistro = numeroRegistro;
		this.fechaMovimiento = fechaMovimiento;
		this.cantidad = cantidad;
		this.referencia = referencia;
		this.valorTotal = valorTotal;
		this.porcentajeIva = porcentajeIva;
		this.costoUnitario = costoUnitario;
		this.placaVehiculo = placaVehiculo;
		this.claseVenta = claseVenta;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
		this.movimientoVendedors = movimientoVendedors;
	}

	public Long getIdMoin() {
		return this.idMoin;
	}

	public void setIdMoin(Long idMoin) {
		this.idMoin = idMoin;
	}

	public Documento getDocumento() {
		return this.documento;
	}

	public void setDocumento(Documento documento) {
		this.documento = documento;
	}

	public Sucursal getSucursalBySucursalRecibeEnvia() {
		return this.sucursalBySucursalRecibeEnvia;
	}

	public void setSucursalBySucursalRecibeEnvia(
			Sucursal sucursalBySucursalRecibeEnvia) {
		this.sucursalBySucursalRecibeEnvia = sucursalBySucursalRecibeEnvia;
	}

	public Causal getCausal() {
		return this.causal;
	}

	public void setCausal(Causal causal) {
		this.causal = causal;
	}

	public Sucursal getSucursalBySucursalEntrega() {
		return this.sucursalBySucursalEntrega;
	}

	public void setSucursalBySucursalEntrega(Sucursal sucursalBySucursalEntrega) {
		this.sucursalBySucursalEntrega = sucursalBySucursalEntrega;
	}

	public ReferenciaSucursal getReferenciaSucursal() {
		return this.referenciaSucursal;
	}

	public void setReferenciaSucursal(ReferenciaSucursal referenciaSucursal) {
		this.referenciaSucursal = referenciaSucursal;
	}

	public Long getNumeroRegistro() {
		return this.numeroRegistro;
	}

	public void setNumeroRegistro(Long numeroRegistro) {
		this.numeroRegistro = numeroRegistro;
	}

	public Date getFechaMovimiento() {
		return this.fechaMovimiento;
	}

	public void setFechaMovimiento(Date fechaMovimiento) {
		this.fechaMovimiento = fechaMovimiento;
	}

	public Double getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Double cantidad) {
		this.cantidad = cantidad;
	}

	public String getReferencia() {
		return this.referencia;
	}

	public void setReferencia(String referencia) {
		this.referencia = referencia;
	}

	public Double getValorTotal() {
		return this.valorTotal;
	}

	public void setValorTotal(Double valorTotal) {
		this.valorTotal = valorTotal;
	}

	public Double getPorcentajeIva() {
		return this.porcentajeIva;
	}

	public void setPorcentajeIva(Double porcentajeIva) {
		this.porcentajeIva = porcentajeIva;
	}

	public Double getCostoUnitario() {
		return this.costoUnitario;
	}

	public void setCostoUnitario(Double costoUnitario) {
		this.costoUnitario = costoUnitario;
	}

	public String getPlacaVehiculo() {
		return this.placaVehiculo;
	}

	public void setPlacaVehiculo(String placaVehiculo) {
		this.placaVehiculo = placaVehiculo;
	}

	public String getClaseVenta() {
		return this.claseVenta;
	}

	public void setClaseVenta(String claseVenta) {
		this.claseVenta = claseVenta;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

	public Set<MovimientoVendedor> getMovimientoVendedors() {
		return this.movimientoVendedors;
	}

	public void setMovimientoVendedors(
			Set<MovimientoVendedor> movimientoVendedors) {
		this.movimientoVendedors = movimientoVendedors;
	}

}
