package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * RboDetalleFormasPago generated by Zathura powered by
 * Hibernate-tools(hbm2java)
 */
public class RboDetalleFormasPago implements java.io.Serializable {

	private Long idRdfp;
	private Documento documento;
	private Banco banco;
	private Recibo recibo;
	private TipoFormaPago tipoFormaPago;
	private ChequePosfechado chequePosfechado;
	private Double montoCancelado;
	private String transaccion;
	private String numeroDocumeto;
	private Date fechaConsignacion;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;
	private Set<Cruce> cruces = new HashSet<Cruce>(0);

	public RboDetalleFormasPago() {
	}

	public RboDetalleFormasPago(Long idRdfp, Recibo recibo,
			Double montoCancelado, Date fechaCreacion, String operCreador,
			Date fechaModificacion, String operModifica, String estadoRegistro) {
		this.idRdfp = idRdfp;
		this.recibo = recibo;
		this.montoCancelado = montoCancelado;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public RboDetalleFormasPago(Long idRdfp, Documento documento, Banco banco,
			Recibo recibo, TipoFormaPago tipoFormaPago,
			ChequePosfechado chequePosfechado, Double montoCancelado,
			String transaccion, String numeroDocumeto, Date fechaConsignacion,
			Date fechaCreacion, String operCreador, Date fechaModificacion,
			String operModifica, String estadoRegistro, Set<Cruce> cruces) {
		this.idRdfp = idRdfp;
		this.documento = documento;
		this.banco = banco;
		this.recibo = recibo;
		this.tipoFormaPago = tipoFormaPago;
		this.chequePosfechado = chequePosfechado;
		this.montoCancelado = montoCancelado;
		this.transaccion = transaccion;
		this.numeroDocumeto = numeroDocumeto;
		this.fechaConsignacion = fechaConsignacion;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
		this.cruces = cruces;
	}

	public Long getIdRdfp() {
		return this.idRdfp;
	}

	public void setIdRdfp(Long idRdfp) {
		this.idRdfp = idRdfp;
	}

	public Documento getDocumento() {
		return this.documento;
	}

	public void setDocumento(Documento documento) {
		this.documento = documento;
	}

	public Banco getBanco() {
		return this.banco;
	}

	public void setBanco(Banco banco) {
		this.banco = banco;
	}

	public Recibo getRecibo() {
		return this.recibo;
	}

	public void setRecibo(Recibo recibo) {
		this.recibo = recibo;
	}

	public TipoFormaPago getTipoFormaPago() {
		return this.tipoFormaPago;
	}

	public void setTipoFormaPago(TipoFormaPago tipoFormaPago) {
		this.tipoFormaPago = tipoFormaPago;
	}

	public ChequePosfechado getChequePosfechado() {
		return this.chequePosfechado;
	}

	public void setChequePosfechado(ChequePosfechado chequePosfechado) {
		this.chequePosfechado = chequePosfechado;
	}

	public Double getMontoCancelado() {
		return this.montoCancelado;
	}

	public void setMontoCancelado(Double montoCancelado) {
		this.montoCancelado = montoCancelado;
	}

	public String getTransaccion() {
		return this.transaccion;
	}

	public void setTransaccion(String transaccion) {
		this.transaccion = transaccion;
	}

	public String getNumeroDocumeto() {
		return this.numeroDocumeto;
	}

	public void setNumeroDocumeto(String numeroDocumeto) {
		this.numeroDocumeto = numeroDocumeto;
	}

	public Date getFechaConsignacion() {
		return this.fechaConsignacion;
	}

	public void setFechaConsignacion(Date fechaConsignacion) {
		this.fechaConsignacion = fechaConsignacion;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

	public Set<Cruce> getCruces() {
		return this.cruces;
	}

	public void setCruces(Set<Cruce> cruces) {
		this.cruces = cruces;
	}

}
