package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * RutaRelacionComercial generated by Zathura powered by
 * Hibernate-tools(hbm2java)
 */
public class RutaRelacionComercial implements java.io.Serializable {

	private Long idRrec;
	private RutaDistribucion rutaDistribucion;
	private AtencionVendedor atencionVendedor;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;
	private Set<LogisticaReversiva> logisticaReversivas = new HashSet<LogisticaReversiva>(
			0);

	public RutaRelacionComercial() {
	}

	public RutaRelacionComercial(Long idRrec,
			RutaDistribucion rutaDistribucion,
			AtencionVendedor atencionVendedor, Date fechaCreacion,
			String operCreador, Date fechaModificacion, String operModifica,
			String estadoRegistro) {
		this.idRrec = idRrec;
		this.rutaDistribucion = rutaDistribucion;
		this.atencionVendedor = atencionVendedor;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public RutaRelacionComercial(Long idRrec,
			RutaDistribucion rutaDistribucion,
			AtencionVendedor atencionVendedor, Date fechaCreacion,
			String operCreador, Date fechaModificacion, String operModifica,
			String estadoRegistro, Set<LogisticaReversiva> logisticaReversivas) {
		this.idRrec = idRrec;
		this.rutaDistribucion = rutaDistribucion;
		this.atencionVendedor = atencionVendedor;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
		this.logisticaReversivas = logisticaReversivas;
	}

	public Long getIdRrec() {
		return this.idRrec;
	}

	public void setIdRrec(Long idRrec) {
		this.idRrec = idRrec;
	}

	public RutaDistribucion getRutaDistribucion() {
		return this.rutaDistribucion;
	}

	public void setRutaDistribucion(RutaDistribucion rutaDistribucion) {
		this.rutaDistribucion = rutaDistribucion;
	}

	public AtencionVendedor getAtencionVendedor() {
		return this.atencionVendedor;
	}

	public void setAtencionVendedor(AtencionVendedor atencionVendedor) {
		this.atencionVendedor = atencionVendedor;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

	public Set<LogisticaReversiva> getLogisticaReversivas() {
		return this.logisticaReversivas;
	}

	public void setLogisticaReversivas(
			Set<LogisticaReversiva> logisticaReversivas) {
		this.logisticaReversivas = logisticaReversivas;
	}

}
