package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * RutaDistribucion generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class RutaDistribucion implements java.io.Serializable {

	private Long idRudi;
	private String codigo;
	private String descripcion;
	private Double tiempoEntrega;
	private Double tiempoTransporte;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;
	private Set<RutaRelacionComercial> rutaRelacionComercials = new HashSet<RutaRelacionComercial>(
			0);

	public RutaDistribucion() {
	}

	public RutaDistribucion(Long idRudi, String codigo, Date fechaCreacion,
			String operCreador, Date fechaModificacion, String operModifica,
			String estadoRegistro) {
		this.idRudi = idRudi;
		this.codigo = codigo;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public RutaDistribucion(Long idRudi, String codigo, String descripcion,
			Double tiempoEntrega, Double tiempoTransporte, Date fechaCreacion,
			String operCreador, Date fechaModificacion, String operModifica,
			String estadoRegistro,
			Set<RutaRelacionComercial> rutaRelacionComercials) {
		this.idRudi = idRudi;
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.tiempoEntrega = tiempoEntrega;
		this.tiempoTransporte = tiempoTransporte;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
		this.rutaRelacionComercials = rutaRelacionComercials;
	}

	public Long getIdRudi() {
		return this.idRudi;
	}

	public void setIdRudi(Long idRudi) {
		this.idRudi = idRudi;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Double getTiempoEntrega() {
		return this.tiempoEntrega;
	}

	public void setTiempoEntrega(Double tiempoEntrega) {
		this.tiempoEntrega = tiempoEntrega;
	}

	public Double getTiempoTransporte() {
		return this.tiempoTransporte;
	}

	public void setTiempoTransporte(Double tiempoTransporte) {
		this.tiempoTransporte = tiempoTransporte;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

	public Set<RutaRelacionComercial> getRutaRelacionComercials() {
		return this.rutaRelacionComercials;
	}

	public void setRutaRelacionComercials(
			Set<RutaRelacionComercial> rutaRelacionComercials) {
		this.rutaRelacionComercials = rutaRelacionComercials;
	}

}
