package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * SolicitudCampo generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class SolicitudCampo implements java.io.Serializable {

	private Long idSoca;
	private SolicitudCambio solicitudCambio;
	private CamposParametrizables camposParametrizables;
	private String valorCadena;
	private Long valorNumerico;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;

	public SolicitudCampo() {
	}

	public SolicitudCampo(Long idSoca, SolicitudCambio solicitudCambio,
			CamposParametrizables camposParametrizables, Date fechaCreacion,
			String operCreador, Date fechaModificacion, String operModifica,
			String estadoRegistro) {
		this.idSoca = idSoca;
		this.solicitudCambio = solicitudCambio;
		this.camposParametrizables = camposParametrizables;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public SolicitudCampo(Long idSoca, SolicitudCambio solicitudCambio,
			CamposParametrizables camposParametrizables, String valorCadena,
			Long valorNumerico, Date fechaCreacion, String operCreador,
			Date fechaModificacion, String operModifica, String estadoRegistro) {
		this.idSoca = idSoca;
		this.solicitudCambio = solicitudCambio;
		this.camposParametrizables = camposParametrizables;
		this.valorCadena = valorCadena;
		this.valorNumerico = valorNumerico;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public Long getIdSoca() {
		return this.idSoca;
	}

	public void setIdSoca(Long idSoca) {
		this.idSoca = idSoca;
	}

	public SolicitudCambio getSolicitudCambio() {
		return this.solicitudCambio;
	}

	public void setSolicitudCambio(SolicitudCambio solicitudCambio) {
		this.solicitudCambio = solicitudCambio;
	}

	public CamposParametrizables getCamposParametrizables() {
		return this.camposParametrizables;
	}

	public void setCamposParametrizables(
			CamposParametrizables camposParametrizables) {
		this.camposParametrizables = camposParametrizables;
	}

	public String getValorCadena() {
		return this.valorCadena;
	}

	public void setValorCadena(String valorCadena) {
		this.valorCadena = valorCadena;
	}

	public Long getValorNumerico() {
		return this.valorNumerico;
	}

	public void setValorNumerico(Long valorNumerico) {
		this.valorNumerico = valorNumerico;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

}
