package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * StockInventarioMensual generated by Zathura powered by
 * Hibernate-tools(hbm2java)
 */
public class StockInventarioMensual implements java.io.Serializable {

	private Long idStin;
	private SaldoInicialInventario saldoInicialInventario;
	private Long ano;
	private Long mes;
	private Double cantidadEntrada;
	private Double cantidadSalidas;
	private Double minimoPedido;
	private Double maximoPedido;
	private Double minimoDistribucion;
	private Double maximoDistribucion;
	private Double costoEntradas;
	private Double costoSalidas;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;

	public StockInventarioMensual() {
	}

	public StockInventarioMensual(Long idStin,
			SaldoInicialInventario saldoInicialInventario, Date fechaCreacion,
			String operCreador, Date fechaModificacion, String operModifica,
			String estadoRegistro) {
		this.idStin = idStin;
		this.saldoInicialInventario = saldoInicialInventario;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public StockInventarioMensual(Long idStin,
			SaldoInicialInventario saldoInicialInventario, Long ano, Long mes,
			Double cantidadEntrada, Double cantidadSalidas,
			Double minimoPedido, Double maximoPedido,
			Double minimoDistribucion, Double maximoDistribucion,
			Double costoEntradas, Double costoSalidas, Date fechaCreacion,
			String operCreador, Date fechaModificacion, String operModifica,
			String estadoRegistro) {
		this.idStin = idStin;
		this.saldoInicialInventario = saldoInicialInventario;
		this.ano = ano;
		this.mes = mes;
		this.cantidadEntrada = cantidadEntrada;
		this.cantidadSalidas = cantidadSalidas;
		this.minimoPedido = minimoPedido;
		this.maximoPedido = maximoPedido;
		this.minimoDistribucion = minimoDistribucion;
		this.maximoDistribucion = maximoDistribucion;
		this.costoEntradas = costoEntradas;
		this.costoSalidas = costoSalidas;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public Long getIdStin() {
		return this.idStin;
	}

	public void setIdStin(Long idStin) {
		this.idStin = idStin;
	}

	public SaldoInicialInventario getSaldoInicialInventario() {
		return this.saldoInicialInventario;
	}

	public void setSaldoInicialInventario(
			SaldoInicialInventario saldoInicialInventario) {
		this.saldoInicialInventario = saldoInicialInventario;
	}

	public Long getAno() {
		return this.ano;
	}

	public void setAno(Long ano) {
		this.ano = ano;
	}

	public Long getMes() {
		return this.mes;
	}

	public void setMes(Long mes) {
		this.mes = mes;
	}

	public Double getCantidadEntrada() {
		return this.cantidadEntrada;
	}

	public void setCantidadEntrada(Double cantidadEntrada) {
		this.cantidadEntrada = cantidadEntrada;
	}

	public Double getCantidadSalidas() {
		return this.cantidadSalidas;
	}

	public void setCantidadSalidas(Double cantidadSalidas) {
		this.cantidadSalidas = cantidadSalidas;
	}

	public Double getMinimoPedido() {
		return this.minimoPedido;
	}

	public void setMinimoPedido(Double minimoPedido) {
		this.minimoPedido = minimoPedido;
	}

	public Double getMaximoPedido() {
		return this.maximoPedido;
	}

	public void setMaximoPedido(Double maximoPedido) {
		this.maximoPedido = maximoPedido;
	}

	public Double getMinimoDistribucion() {
		return this.minimoDistribucion;
	}

	public void setMinimoDistribucion(Double minimoDistribucion) {
		this.minimoDistribucion = minimoDistribucion;
	}

	public Double getMaximoDistribucion() {
		return this.maximoDistribucion;
	}

	public void setMaximoDistribucion(Double maximoDistribucion) {
		this.maximoDistribucion = maximoDistribucion;
	}

	public Double getCostoEntradas() {
		return this.costoEntradas;
	}

	public void setCostoEntradas(Double costoEntradas) {
		this.costoEntradas = costoEntradas;
	}

	public Double getCostoSalidas() {
		return this.costoSalidas;
	}

	public void setCostoSalidas(Double costoSalidas) {
		this.costoSalidas = costoSalidas;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

}
