package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Sucursal generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class Sucursal implements java.io.Serializable {

	private Long idSucu;
	private Persona persona;
	private RegionalGeografica regionalGeografica;
	private Empresa empresa;
	private DivisionPolitica divisionPolitica;
	private Sucursal sucursal;
	private TipoSucursal tipoSucursal;
	private String codigo;
	private String nombre;
	private String direccion;
	private String telefono;
	private String zipCode;
	private String email;
	private String estadoSucursal;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;
	private Set<RboDetalleDocumentos> rboDetalleDocumentoses = new HashSet<RboDetalleDocumentos>(
			0);
	private Set<ClavesParaRotar> clavesParaRotars = new HashSet<ClavesParaRotar>(
			0);
	private Set<ConsecutivoDocumento> consecutivoDocumentos = new HashSet<ConsecutivoDocumento>(
			0);
	private Set<DescuentoComercial> descuentoComercialsForSucursal = new HashSet<DescuentoComercial>(
			0);
	private Set<RelacionComercial> relacionComercialsForSucursalHija = new HashSet<RelacionComercial>(
			0);
	private Set<Sucursal> sucursals = new HashSet<Sucursal>(0);
	private Set<ListaPreciosEspeciales> listaPreciosEspecialesesForIdSucu = new HashSet<ListaPreciosEspeciales>(
			0);
	private Set<OrdenesDeCompra> ordenesDeCompras = new HashSet<OrdenesDeCompra>(
			0);
	private Set<Contacto> contactos = new HashSet<Contacto>(0);
	private Set<Bateriologo> bateriologos = new HashSet<Bateriologo>(0);
	private Set<Multifamilia> multifamilias = new HashSet<Multifamilia>(0);
	private Set<Documento> documentos = new HashSet<Documento>(0);
	private Set<MovimientoInventario> movimientoInventariosForSucursalEntrega = new HashSet<MovimientoInventario>(
			0);
	private Set<ListaPrecios> listaPrecioses = new HashSet<ListaPrecios>(0);
	private Set<MovimientoInventario> movimientoInventariosForSucursalRecibeEnvia = new HashSet<MovimientoInventario>(
			0);
	private Set<DescuentoComercial> descuentoComercialsForIdSucu = new HashSet<DescuentoComercial>(
			0);
	private Set<ListaPreciosEspeciales> listaPreciosEspecialesesForSucursal = new HashSet<ListaPreciosEspeciales>(
			0);
	private Set<RelacionComercial> relacionComercialsForSucursalPadre = new HashSet<RelacionComercial>(
			0);
	private Set<ReferenciaSucursal> referenciaSucursals = new HashSet<ReferenciaSucursal>(
			0);
	private Set<PronosticoVenta> pronosticoVentas = new HashSet<PronosticoVenta>(
			0);
	private Set<Vendedor> vendedors = new HashSet<Vendedor>(0);

	public Sucursal() {
	}

	public Sucursal(Long idSucu, String estadoSucursal, Date fechaCreacion,
			String operCreador, Date fechaModificacion, String operModifica,
			String estadoRegistro) {
		this.idSucu = idSucu;
		this.estadoSucursal = estadoSucursal;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public Sucursal(
			Long idSucu,
			Persona persona,
			RegionalGeografica regionalGeografica,
			Empresa empresa,
			DivisionPolitica divisionPolitica,
			Sucursal sucursal,
			TipoSucursal tipoSucursal,
			String codigo,
			String nombre,
			String direccion,
			String telefono,
			String zipCode,
			String email,
			String estadoSucursal,
			Date fechaCreacion,
			String operCreador,
			Date fechaModificacion,
			String operModifica,
			String estadoRegistro,
			Set<RboDetalleDocumentos> rboDetalleDocumentoses,
			Set<ClavesParaRotar> clavesParaRotars,
			Set<ConsecutivoDocumento> consecutivoDocumentos,
			Set<DescuentoComercial> descuentoComercialsForSucursal,
			Set<RelacionComercial> relacionComercialsForSucursalHija,
			Set<Sucursal> sucursals,
			Set<ListaPreciosEspeciales> listaPreciosEspecialesesForIdSucu,
			Set<OrdenesDeCompra> ordenesDeCompras,
			Set<Contacto> contactos,
			Set<Bateriologo> bateriologos,
			Set<Multifamilia> multifamilias,
			Set<Documento> documentos,
			Set<MovimientoInventario> movimientoInventariosForSucursalEntrega,
			Set<ListaPrecios> listaPrecioses,
			Set<MovimientoInventario> movimientoInventariosForSucursalRecibeEnvia,
			Set<DescuentoComercial> descuentoComercialsForIdSucu,
			Set<ListaPreciosEspeciales> listaPreciosEspecialesesForSucursal,
			Set<RelacionComercial> relacionComercialsForSucursalPadre,
			Set<ReferenciaSucursal> referenciaSucursals,
			Set<PronosticoVenta> pronosticoVentas, Set<Vendedor> vendedors) {
		this.idSucu = idSucu;
		this.persona = persona;
		this.regionalGeografica = regionalGeografica;
		this.empresa = empresa;
		this.divisionPolitica = divisionPolitica;
		this.sucursal = sucursal;
		this.tipoSucursal = tipoSucursal;
		this.codigo = codigo;
		this.nombre = nombre;
		this.direccion = direccion;
		this.telefono = telefono;
		this.zipCode = zipCode;
		this.email = email;
		this.estadoSucursal = estadoSucursal;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
		this.rboDetalleDocumentoses = rboDetalleDocumentoses;
		this.clavesParaRotars = clavesParaRotars;
		this.consecutivoDocumentos = consecutivoDocumentos;
		this.descuentoComercialsForSucursal = descuentoComercialsForSucursal;
		this.relacionComercialsForSucursalHija = relacionComercialsForSucursalHija;
		this.sucursals = sucursals;
		this.listaPreciosEspecialesesForIdSucu = listaPreciosEspecialesesForIdSucu;
		this.ordenesDeCompras = ordenesDeCompras;
		this.contactos = contactos;
		this.bateriologos = bateriologos;
		this.multifamilias = multifamilias;
		this.documentos = documentos;
		this.movimientoInventariosForSucursalEntrega = movimientoInventariosForSucursalEntrega;
		this.listaPrecioses = listaPrecioses;
		this.movimientoInventariosForSucursalRecibeEnvia = movimientoInventariosForSucursalRecibeEnvia;
		this.descuentoComercialsForIdSucu = descuentoComercialsForIdSucu;
		this.listaPreciosEspecialesesForSucursal = listaPreciosEspecialesesForSucursal;
		this.relacionComercialsForSucursalPadre = relacionComercialsForSucursalPadre;
		this.referenciaSucursals = referenciaSucursals;
		this.pronosticoVentas = pronosticoVentas;
		this.vendedors = vendedors;
	}

	public Long getIdSucu() {
		return this.idSucu;
	}

	public void setIdSucu(Long idSucu) {
		this.idSucu = idSucu;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public RegionalGeografica getRegionalGeografica() {
		return this.regionalGeografica;
	}

	public void setRegionalGeografica(RegionalGeografica regionalGeografica) {
		this.regionalGeografica = regionalGeografica;
	}

	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	public DivisionPolitica getDivisionPolitica() {
		return this.divisionPolitica;
	}

	public void setDivisionPolitica(DivisionPolitica divisionPolitica) {
		this.divisionPolitica = divisionPolitica;
	}

	public Sucursal getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Sucursal sucursal) {
		this.sucursal = sucursal;
	}

	public TipoSucursal getTipoSucursal() {
		return this.tipoSucursal;
	}

	public void setTipoSucursal(TipoSucursal tipoSucursal) {
		this.tipoSucursal = tipoSucursal;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getEstadoSucursal() {
		return this.estadoSucursal;
	}

	public void setEstadoSucursal(String estadoSucursal) {
		this.estadoSucursal = estadoSucursal;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

	public Set<RboDetalleDocumentos> getRboDetalleDocumentoses() {
		return this.rboDetalleDocumentoses;
	}

	public void setRboDetalleDocumentoses(
			Set<RboDetalleDocumentos> rboDetalleDocumentoses) {
		this.rboDetalleDocumentoses = rboDetalleDocumentoses;
	}

	public Set<ClavesParaRotar> getClavesParaRotars() {
		return this.clavesParaRotars;
	}

	public void setClavesParaRotars(Set<ClavesParaRotar> clavesParaRotars) {
		this.clavesParaRotars = clavesParaRotars;
	}

	public Set<ConsecutivoDocumento> getConsecutivoDocumentos() {
		return this.consecutivoDocumentos;
	}

	public void setConsecutivoDocumentos(
			Set<ConsecutivoDocumento> consecutivoDocumentos) {
		this.consecutivoDocumentos = consecutivoDocumentos;
	}

	public Set<DescuentoComercial> getDescuentoComercialsForSucursal() {
		return this.descuentoComercialsForSucursal;
	}

	public void setDescuentoComercialsForSucursal(
			Set<DescuentoComercial> descuentoComercialsForSucursal) {
		this.descuentoComercialsForSucursal = descuentoComercialsForSucursal;
	}

	public Set<RelacionComercial> getRelacionComercialsForSucursalHija() {
		return this.relacionComercialsForSucursalHija;
	}

	public void setRelacionComercialsForSucursalHija(
			Set<RelacionComercial> relacionComercialsForSucursalHija) {
		this.relacionComercialsForSucursalHija = relacionComercialsForSucursalHija;
	}

	public Set<Sucursal> getSucursals() {
		return this.sucursals;
	}

	public void setSucursals(Set<Sucursal> sucursals) {
		this.sucursals = sucursals;
	}

	public Set<ListaPreciosEspeciales> getListaPreciosEspecialesesForIdSucu() {
		return this.listaPreciosEspecialesesForIdSucu;
	}

	public void setListaPreciosEspecialesesForIdSucu(
			Set<ListaPreciosEspeciales> listaPreciosEspecialesesForIdSucu) {
		this.listaPreciosEspecialesesForIdSucu = listaPreciosEspecialesesForIdSucu;
	}

	public Set<OrdenesDeCompra> getOrdenesDeCompras() {
		return this.ordenesDeCompras;
	}

	public void setOrdenesDeCompras(Set<OrdenesDeCompra> ordenesDeCompras) {
		this.ordenesDeCompras = ordenesDeCompras;
	}

	public Set<Contacto> getContactos() {
		return this.contactos;
	}

	public void setContactos(Set<Contacto> contactos) {
		this.contactos = contactos;
	}

	public Set<Bateriologo> getBateriologos() {
		return this.bateriologos;
	}

	public void setBateriologos(Set<Bateriologo> bateriologos) {
		this.bateriologos = bateriologos;
	}

	public Set<Multifamilia> getMultifamilias() {
		return this.multifamilias;
	}

	public void setMultifamilias(Set<Multifamilia> multifamilias) {
		this.multifamilias = multifamilias;
	}

	public Set<Documento> getDocumentos() {
		return this.documentos;
	}

	public void setDocumentos(Set<Documento> documentos) {
		this.documentos = documentos;
	}

	public Set<MovimientoInventario> getMovimientoInventariosForSucursalEntrega() {
		return this.movimientoInventariosForSucursalEntrega;
	}

	public void setMovimientoInventariosForSucursalEntrega(
			Set<MovimientoInventario> movimientoInventariosForSucursalEntrega) {
		this.movimientoInventariosForSucursalEntrega = movimientoInventariosForSucursalEntrega;
	}

	public Set<ListaPrecios> getListaPrecioses() {
		return this.listaPrecioses;
	}

	public void setListaPrecioses(Set<ListaPrecios> listaPrecioses) {
		this.listaPrecioses = listaPrecioses;
	}

	public Set<MovimientoInventario> getMovimientoInventariosForSucursalRecibeEnvia() {
		return this.movimientoInventariosForSucursalRecibeEnvia;
	}

	public void setMovimientoInventariosForSucursalRecibeEnvia(
			Set<MovimientoInventario> movimientoInventariosForSucursalRecibeEnvia) {
		this.movimientoInventariosForSucursalRecibeEnvia = movimientoInventariosForSucursalRecibeEnvia;
	}

	public Set<DescuentoComercial> getDescuentoComercialsForIdSucu() {
		return this.descuentoComercialsForIdSucu;
	}

	public void setDescuentoComercialsForIdSucu(
			Set<DescuentoComercial> descuentoComercialsForIdSucu) {
		this.descuentoComercialsForIdSucu = descuentoComercialsForIdSucu;
	}

	public Set<ListaPreciosEspeciales> getListaPreciosEspecialesesForSucursal() {
		return this.listaPreciosEspecialesesForSucursal;
	}

	public void setListaPreciosEspecialesesForSucursal(
			Set<ListaPreciosEspeciales> listaPreciosEspecialesesForSucursal) {
		this.listaPreciosEspecialesesForSucursal = listaPreciosEspecialesesForSucursal;
	}

	public Set<RelacionComercial> getRelacionComercialsForSucursalPadre() {
		return this.relacionComercialsForSucursalPadre;
	}

	public void setRelacionComercialsForSucursalPadre(
			Set<RelacionComercial> relacionComercialsForSucursalPadre) {
		this.relacionComercialsForSucursalPadre = relacionComercialsForSucursalPadre;
	}

	public Set<ReferenciaSucursal> getReferenciaSucursals() {
		return this.referenciaSucursals;
	}

	public void setReferenciaSucursals(
			Set<ReferenciaSucursal> referenciaSucursals) {
		this.referenciaSucursals = referenciaSucursals;
	}

	public Set<PronosticoVenta> getPronosticoVentas() {
		return this.pronosticoVentas;
	}

	public void setPronosticoVentas(Set<PronosticoVenta> pronosticoVentas) {
		this.pronosticoVentas = pronosticoVentas;
	}

	public Set<Vendedor> getVendedors() {
		return this.vendedors;
	}

	public void setVendedors(Set<Vendedor> vendedors) {
		this.vendedors = vendedors;
	}

}
