package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tabla generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class Tabla implements java.io.Serializable {

	private Long idTabl;
	private String nombre;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;
	private Set<CamposParametrizables> camposParametrizableses = new HashSet<CamposParametrizables>(
			0);

	public Tabla() {
	}

	public Tabla(Long idTabl, String nombre, Date fechaCreacion,
			String operCreador, Date fechaModificacion, String operModifica,
			String estadoRegistro) {
		this.idTabl = idTabl;
		this.nombre = nombre;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public Tabla(Long idTabl, String nombre, Date fechaCreacion,
			String operCreador, Date fechaModificacion, String operModifica,
			String estadoRegistro,
			Set<CamposParametrizables> camposParametrizableses) {
		this.idTabl = idTabl;
		this.nombre = nombre;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
		this.camposParametrizableses = camposParametrizableses;
	}

	public Long getIdTabl() {
		return this.idTabl;
	}

	public void setIdTabl(Long idTabl) {
		this.idTabl = idTabl;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

	public Set<CamposParametrizables> getCamposParametrizableses() {
		return this.camposParametrizableses;
	}

	public void setCamposParametrizableses(
			Set<CamposParametrizables> camposParametrizableses) {
		this.camposParametrizableses = camposParametrizableses;
	}

}
