package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UnidadVenta generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class UnidadVenta implements java.io.Serializable {

	private Long idUnve;
	private Vendedor vendedor;
	private UnidadNegocio unidadNegocio;
	private String activo;
	private Date fechaInactivo;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;
	private Set<PronosticoVenta> pronosticoVentas = new HashSet<PronosticoVenta>(
			0);
	private Set<Documento> documentosForIdUnve = new HashSet<Documento>(0);
	private Set<MovimientoVendedor> movimientoVendedors = new HashSet<MovimientoVendedor>(
			0);
	private Set<Recibo> recibos = new HashSet<Recibo>(0);
	private Set<RboDetalleDocumentos> rboDetalleDocumentoses = new HashSet<RboDetalleDocumentos>(
			0);
	private Set<PresupuestoVentas> presupuestoVentases = new HashSet<PresupuestoVentas>(
			0);
	private Set<PresupuestoCartera> presupuestoCarteras = new HashSet<PresupuestoCartera>(
			0);
	private Set<Documento> documentosForIdTelemercaderista = new HashSet<Documento>(
			0);

	public UnidadVenta() {
	}

	public UnidadVenta(Long idUnve, Vendedor vendedor,
			UnidadNegocio unidadNegocio, Date fechaCreacion,
			String operCreador, Date fechaModificacion, String operModifica,
			String estadoRegistro) {
		this.idUnve = idUnve;
		this.vendedor = vendedor;
		this.unidadNegocio = unidadNegocio;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public UnidadVenta(Long idUnve, Vendedor vendedor,
			UnidadNegocio unidadNegocio, String activo, Date fechaInactivo,
			Date fechaCreacion, String operCreador, Date fechaModificacion,
			String operModifica, String estadoRegistro,
			Set<PronosticoVenta> pronosticoVentas,
			Set<Documento> documentosForIdUnve,
			Set<MovimientoVendedor> movimientoVendedors, Set<Recibo> recibos,
			Set<RboDetalleDocumentos> rboDetalleDocumentoses,
			Set<PresupuestoVentas> presupuestoVentases,
			Set<PresupuestoCartera> presupuestoCarteras,
			Set<Documento> documentosForIdTelemercaderista) {
		this.idUnve = idUnve;
		this.vendedor = vendedor;
		this.unidadNegocio = unidadNegocio;
		this.activo = activo;
		this.fechaInactivo = fechaInactivo;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
		this.pronosticoVentas = pronosticoVentas;
		this.documentosForIdUnve = documentosForIdUnve;
		this.movimientoVendedors = movimientoVendedors;
		this.recibos = recibos;
		this.rboDetalleDocumentoses = rboDetalleDocumentoses;
		this.presupuestoVentases = presupuestoVentases;
		this.presupuestoCarteras = presupuestoCarteras;
		this.documentosForIdTelemercaderista = documentosForIdTelemercaderista;
	}

	public Long getIdUnve() {
		return this.idUnve;
	}

	public void setIdUnve(Long idUnve) {
		this.idUnve = idUnve;
	}

	public Vendedor getVendedor() {
		return this.vendedor;
	}

	public void setVendedor(Vendedor vendedor) {
		this.vendedor = vendedor;
	}

	public UnidadNegocio getUnidadNegocio() {
		return this.unidadNegocio;
	}

	public void setUnidadNegocio(UnidadNegocio unidadNegocio) {
		this.unidadNegocio = unidadNegocio;
	}

	public String getActivo() {
		return this.activo;
	}

	public void setActivo(String activo) {
		this.activo = activo;
	}

	public Date getFechaInactivo() {
		return this.fechaInactivo;
	}

	public void setFechaInactivo(Date fechaInactivo) {
		this.fechaInactivo = fechaInactivo;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

	public Set<PronosticoVenta> getPronosticoVentas() {
		return this.pronosticoVentas;
	}

	public void setPronosticoVentas(Set<PronosticoVenta> pronosticoVentas) {
		this.pronosticoVentas = pronosticoVentas;
	}

	public Set<Documento> getDocumentosForIdUnve() {
		return this.documentosForIdUnve;
	}

	public void setDocumentosForIdUnve(Set<Documento> documentosForIdUnve) {
		this.documentosForIdUnve = documentosForIdUnve;
	}

	public Set<MovimientoVendedor> getMovimientoVendedors() {
		return this.movimientoVendedors;
	}

	public void setMovimientoVendedors(
			Set<MovimientoVendedor> movimientoVendedors) {
		this.movimientoVendedors = movimientoVendedors;
	}

	public Set<Recibo> getRecibos() {
		return this.recibos;
	}

	public void setRecibos(Set<Recibo> recibos) {
		this.recibos = recibos;
	}

	public Set<RboDetalleDocumentos> getRboDetalleDocumentoses() {
		return this.rboDetalleDocumentoses;
	}

	public void setRboDetalleDocumentoses(
			Set<RboDetalleDocumentos> rboDetalleDocumentoses) {
		this.rboDetalleDocumentoses = rboDetalleDocumentoses;
	}

	public Set<PresupuestoVentas> getPresupuestoVentases() {
		return this.presupuestoVentases;
	}

	public void setPresupuestoVentases(
			Set<PresupuestoVentas> presupuestoVentases) {
		this.presupuestoVentases = presupuestoVentases;
	}

	public Set<PresupuestoCartera> getPresupuestoCarteras() {
		return this.presupuestoCarteras;
	}

	public void setPresupuestoCarteras(
			Set<PresupuestoCartera> presupuestoCarteras) {
		this.presupuestoCarteras = presupuestoCarteras;
	}

	public Set<Documento> getDocumentosForIdTelemercaderista() {
		return this.documentosForIdTelemercaderista;
	}

	public void setDocumentosForIdTelemercaderista(
			Set<Documento> documentosForIdTelemercaderista) {
		this.documentosForIdTelemercaderista = documentosForIdTelemercaderista;
	}

}
