package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AtencionVendedor generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class AtencionVendedor implements java.io.Serializable {

	private Long idAtve;
	private Vendedor vendedor;
	private RelacionComercial relacionComercial;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;
	private Set<ProgramacionAdicional> programacionAdicionals = new HashSet<ProgramacionAdicional>(
			0);
	private Set<Contacto> contactos = new HashSet<Contacto>(0);
	private Set<ProgramacionVisitas> programacionVisitases = new HashSet<ProgramacionVisitas>(
			0);
	private Set<RutaRelacionComercial> rutaRelacionComercials = new HashSet<RutaRelacionComercial>(
			0);

	public AtencionVendedor() {
	}

	public AtencionVendedor(Long idAtve, Vendedor vendedor,
			RelacionComercial relacionComercial, Date fechaCreacion,
			String operCreador, Date fechaModificacion, String operModifica,
			String estadoRegistro) {
		this.idAtve = idAtve;
		this.vendedor = vendedor;
		this.relacionComercial = relacionComercial;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public AtencionVendedor(Long idAtve, Vendedor vendedor,
			RelacionComercial relacionComercial, Date fechaCreacion,
			String operCreador, Date fechaModificacion, String operModifica,
			String estadoRegistro,
			Set<ProgramacionAdicional> programacionAdicionals,
			Set<Contacto> contactos,
			Set<ProgramacionVisitas> programacionVisitases,
			Set<RutaRelacionComercial> rutaRelacionComercials) {
		this.idAtve = idAtve;
		this.vendedor = vendedor;
		this.relacionComercial = relacionComercial;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
		this.programacionAdicionals = programacionAdicionals;
		this.contactos = contactos;
		this.programacionVisitases = programacionVisitases;
		this.rutaRelacionComercials = rutaRelacionComercials;
	}

	public Long getIdAtve() {
		return this.idAtve;
	}

	public void setIdAtve(Long idAtve) {
		this.idAtve = idAtve;
	}

	public Vendedor getVendedor() {
		return this.vendedor;
	}

	public void setVendedor(Vendedor vendedor) {
		this.vendedor = vendedor;
	}

	public RelacionComercial getRelacionComercial() {
		return this.relacionComercial;
	}

	public void setRelacionComercial(RelacionComercial relacionComercial) {
		this.relacionComercial = relacionComercial;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

	public Set<ProgramacionAdicional> getProgramacionAdicionals() {
		return this.programacionAdicionals;
	}

	public void setProgramacionAdicionals(
			Set<ProgramacionAdicional> programacionAdicionals) {
		this.programacionAdicionals = programacionAdicionals;
	}

	public Set<Contacto> getContactos() {
		return this.contactos;
	}

	public void setContactos(Set<Contacto> contactos) {
		this.contactos = contactos;
	}

	public Set<ProgramacionVisitas> getProgramacionVisitases() {
		return this.programacionVisitases;
	}

	public void setProgramacionVisitases(
			Set<ProgramacionVisitas> programacionVisitases) {
		this.programacionVisitases = programacionVisitases;
	}

	public Set<RutaRelacionComercial> getRutaRelacionComercials() {
		return this.rutaRelacionComercials;
	}

	public void setRutaRelacionComercials(
			Set<RutaRelacionComercial> rutaRelacionComercials) {
		this.rutaRelacionComercials = rutaRelacionComercials;
	}

}
