package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Banco generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class Banco implements java.io.Serializable {

	private Long idBanc;
	private String codigo;
	private String descripcion;
	private Long consigna;
	private Long confirmaCheque;
	private String cuentaBanco;
	private String cuentaDescuento;
	private Long manejaBeneficiario;
	private Long importaPda;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;
	private Set<RboDetalleFormasPago> rboDetalleFormasPagos = new HashSet<RboDetalleFormasPago>(
			0);

	public Banco() {
	}

	public Banco(Long idBanc, String codigo, String descripcion,
			Date fechaCreacion, String operCreador, Date fechaModificacion,
			String operModifica, String estadoRegistro) {
		this.idBanc = idBanc;
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public Banco(Long idBanc, String codigo, String descripcion, Long consigna,
			Long confirmaCheque, String cuentaBanco, String cuentaDescuento,
			Long manejaBeneficiario, Long importaPda, Date fechaCreacion,
			String operCreador, Date fechaModificacion, String operModifica,
			String estadoRegistro,
			Set<RboDetalleFormasPago> rboDetalleFormasPagos) {
		this.idBanc = idBanc;
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.consigna = consigna;
		this.confirmaCheque = confirmaCheque;
		this.cuentaBanco = cuentaBanco;
		this.cuentaDescuento = cuentaDescuento;
		this.manejaBeneficiario = manejaBeneficiario;
		this.importaPda = importaPda;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
		this.rboDetalleFormasPagos = rboDetalleFormasPagos;
	}

	public Long getIdBanc() {
		return this.idBanc;
	}

	public void setIdBanc(Long idBanc) {
		this.idBanc = idBanc;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Long getConsigna() {
		return this.consigna;
	}

	public void setConsigna(Long consigna) {
		this.consigna = consigna;
	}

	public Long getConfirmaCheque() {
		return this.confirmaCheque;
	}

	public void setConfirmaCheque(Long confirmaCheque) {
		this.confirmaCheque = confirmaCheque;
	}

	public String getCuentaBanco() {
		return this.cuentaBanco;
	}

	public void setCuentaBanco(String cuentaBanco) {
		this.cuentaBanco = cuentaBanco;
	}

	public String getCuentaDescuento() {
		return this.cuentaDescuento;
	}

	public void setCuentaDescuento(String cuentaDescuento) {
		this.cuentaDescuento = cuentaDescuento;
	}

	public Long getManejaBeneficiario() {
		return this.manejaBeneficiario;
	}

	public void setManejaBeneficiario(Long manejaBeneficiario) {
		this.manejaBeneficiario = manejaBeneficiario;
	}

	public Long getImportaPda() {
		return this.importaPda;
	}

	public void setImportaPda(Long importaPda) {
		this.importaPda = importaPda;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

	public Set<RboDetalleFormasPago> getRboDetalleFormasPagos() {
		return this.rboDetalleFormasPagos;
	}

	public void setRboDetalleFormasPagos(
			Set<RboDetalleFormasPago> rboDetalleFormasPagos) {
		this.rboDetalleFormasPagos = rboDetalleFormasPagos;
	}

}
