package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Causal generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class Causal implements java.io.Serializable {

	private Long idCusa;
	private TipoCausal tipoCausal;
	private Long codigo;
	private String descripcion;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;
	private Set<MovimientoInventario> movimientoInventarios = new HashSet<MovimientoInventario>(
			0);
	private Set<Visita> visitas = new HashSet<Visita>(0);
	private Set<ProgramacionAdicional> programacionAdicionals = new HashSet<ProgramacionAdicional>(
			0);
	private Set<Documento> documentos = new HashSet<Documento>(0);

	public Causal() {
	}

	public Causal(Long idCusa, TipoCausal tipoCausal, Long codigo,
			String descripcion, Date fechaCreacion, String operCreador,
			Date fechaModificacion, String operModifica, String estadoRegistro) {
		this.idCusa = idCusa;
		this.tipoCausal = tipoCausal;
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public Causal(Long idCusa, TipoCausal tipoCausal, Long codigo,
			String descripcion, Date fechaCreacion, String operCreador,
			Date fechaModificacion, String operModifica, String estadoRegistro,
			Set<MovimientoInventario> movimientoInventarios,
			Set<Visita> visitas,
			Set<ProgramacionAdicional> programacionAdicionals,
			Set<Documento> documentos) {
		this.idCusa = idCusa;
		this.tipoCausal = tipoCausal;
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
		this.movimientoInventarios = movimientoInventarios;
		this.visitas = visitas;
		this.programacionAdicionals = programacionAdicionals;
		this.documentos = documentos;
	}

	public Long getIdCusa() {
		return this.idCusa;
	}

	public void setIdCusa(Long idCusa) {
		this.idCusa = idCusa;
	}

	public TipoCausal getTipoCausal() {
		return this.tipoCausal;
	}

	public void setTipoCausal(TipoCausal tipoCausal) {
		this.tipoCausal = tipoCausal;
	}

	public Long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

	public Set<MovimientoInventario> getMovimientoInventarios() {
		return this.movimientoInventarios;
	}

	public void setMovimientoInventarios(
			Set<MovimientoInventario> movimientoInventarios) {
		this.movimientoInventarios = movimientoInventarios;
	}

	public Set<Visita> getVisitas() {
		return this.visitas;
	}

	public void setVisitas(Set<Visita> visitas) {
		this.visitas = visitas;
	}

	public Set<ProgramacionAdicional> getProgramacionAdicionals() {
		return this.programacionAdicionals;
	}

	public void setProgramacionAdicionals(
			Set<ProgramacionAdicional> programacionAdicionals) {
		this.programacionAdicionals = programacionAdicionals;
	}

	public Set<Documento> getDocumentos() {
		return this.documentos;
	}

	public void setDocumentos(Set<Documento> documentos) {
		this.documentos = documentos;
	}

}
