package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Documento generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class Documento implements java.io.Serializable {

	private Long idDocu;
	private EstadoDocumento estadoDocumento;
	private ConsecutivoDocumento consecutivoDocumento;
	private TipoDocumento tipoDocumento;
	private Causal causal;
	private UnidadVenta unidadVentaByIdTelemercaderista;
	private UnidadVenta unidadVentaByIdUnve;
	private RelacionComercial relacionComercial;
	private Sucursal sucursal;
	private Long numeroDocumento;
	private String numeroDefinitivo;
	private Double valorTotal;
	private Date fechaDocumento;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;
	private Set<OrdenesDeCompra> ordenesDeCompras = new HashSet<OrdenesDeCompra>(
			0);
	private Set<LogisticaReversiva> logisticaReversivasForDocumentoAutorizacion = new HashSet<LogisticaReversiva>(
			0);
	private Set<Pedido> pedidos = new HashSet<Pedido>(0);
	private Set<DetalleVisita> detalleVisitas = new HashSet<DetalleVisita>(0);
	private Set<Garantia> garantias = new HashSet<Garantia>(0);
	private Set<RboDetalleFormasPago> rboDetalleFormasPagos = new HashSet<RboDetalleFormasPago>(
			0);
	private Set<Recibo> recibos = new HashSet<Recibo>(0);
	private Set<RboDetalleDocumentos> rboDetalleDocumentoses = new HashSet<RboDetalleDocumentos>(
			0);
	private Set<ItemRotacion> itemRotacions = new HashSet<ItemRotacion>(0);
	private Set<LogisticaReversiva> logisticaReversivasForDocumentoSolicitud = new HashSet<LogisticaReversiva>(
			0);
	private Set<LogisticaReversiva> logisticaReversivasForDocumentoRecoleccion = new HashSet<LogisticaReversiva>(
			0);
	private Set<Cartera> carteras = new HashSet<Cartera>(0);
	private Set<MovimientoInventario> movimientoInventarios = new HashSet<MovimientoInventario>(
			0);

	public Documento() {
	}

	public Documento(Long idDocu, EstadoDocumento estadoDocumento,
			TipoDocumento tipoDocumento, Sucursal sucursal, Date fechaCreacion,
			String operCreador, Date fechaModificacion, String operModifica,
			String estadoRegistro) {
		this.idDocu = idDocu;
		this.estadoDocumento = estadoDocumento;
		this.tipoDocumento = tipoDocumento;
		this.sucursal = sucursal;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public Documento(
			Long idDocu,
			EstadoDocumento estadoDocumento,
			ConsecutivoDocumento consecutivoDocumento,
			TipoDocumento tipoDocumento,
			Causal causal,
			UnidadVenta unidadVentaByIdTelemercaderista,
			UnidadVenta unidadVentaByIdUnve,
			RelacionComercial relacionComercial,
			Sucursal sucursal,
			Long numeroDocumento,
			String numeroDefinitivo,
			Double valorTotal,
			Date fechaDocumento,
			Date fechaCreacion,
			String operCreador,
			Date fechaModificacion,
			String operModifica,
			String estadoRegistro,
			Set<OrdenesDeCompra> ordenesDeCompras,
			Set<LogisticaReversiva> logisticaReversivasForDocumentoAutorizacion,
			Set<Pedido> pedidos, Set<DetalleVisita> detalleVisitas,
			Set<Garantia> garantias,
			Set<RboDetalleFormasPago> rboDetalleFormasPagos,
			Set<Recibo> recibos,
			Set<RboDetalleDocumentos> rboDetalleDocumentoses,
			Set<ItemRotacion> itemRotacions,
			Set<LogisticaReversiva> logisticaReversivasForDocumentoSolicitud,
			Set<LogisticaReversiva> logisticaReversivasForDocumentoRecoleccion,
			Set<Cartera> carteras,
			Set<MovimientoInventario> movimientoInventarios) {
		this.idDocu = idDocu;
		this.estadoDocumento = estadoDocumento;
		this.consecutivoDocumento = consecutivoDocumento;
		this.tipoDocumento = tipoDocumento;
		this.causal = causal;
		this.unidadVentaByIdTelemercaderista = unidadVentaByIdTelemercaderista;
		this.unidadVentaByIdUnve = unidadVentaByIdUnve;
		this.relacionComercial = relacionComercial;
		this.sucursal = sucursal;
		this.numeroDocumento = numeroDocumento;
		this.numeroDefinitivo = numeroDefinitivo;
		this.valorTotal = valorTotal;
		this.fechaDocumento = fechaDocumento;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
		this.ordenesDeCompras = ordenesDeCompras;
		this.logisticaReversivasForDocumentoAutorizacion = logisticaReversivasForDocumentoAutorizacion;
		this.pedidos = pedidos;
		this.detalleVisitas = detalleVisitas;
		this.garantias = garantias;
		this.rboDetalleFormasPagos = rboDetalleFormasPagos;
		this.recibos = recibos;
		this.rboDetalleDocumentoses = rboDetalleDocumentoses;
		this.itemRotacions = itemRotacions;
		this.logisticaReversivasForDocumentoSolicitud = logisticaReversivasForDocumentoSolicitud;
		this.logisticaReversivasForDocumentoRecoleccion = logisticaReversivasForDocumentoRecoleccion;
		this.carteras = carteras;
		this.movimientoInventarios = movimientoInventarios;
	}

	public Long getIdDocu() {
		return this.idDocu;
	}

	public void setIdDocu(Long idDocu) {
		this.idDocu = idDocu;
	}

	public EstadoDocumento getEstadoDocumento() {
		return this.estadoDocumento;
	}

	public void setEstadoDocumento(EstadoDocumento estadoDocumento) {
		this.estadoDocumento = estadoDocumento;
	}

	public ConsecutivoDocumento getConsecutivoDocumento() {
		return this.consecutivoDocumento;
	}

	public void setConsecutivoDocumento(
			ConsecutivoDocumento consecutivoDocumento) {
		this.consecutivoDocumento = consecutivoDocumento;
	}

	public TipoDocumento getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(TipoDocumento tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	public Causal getCausal() {
		return this.causal;
	}

	public void setCausal(Causal causal) {
		this.causal = causal;
	}

	public UnidadVenta getUnidadVentaByIdTelemercaderista() {
		return this.unidadVentaByIdTelemercaderista;
	}

	public void setUnidadVentaByIdTelemercaderista(
			UnidadVenta unidadVentaByIdTelemercaderista) {
		this.unidadVentaByIdTelemercaderista = unidadVentaByIdTelemercaderista;
	}

	public UnidadVenta getUnidadVentaByIdUnve() {
		return this.unidadVentaByIdUnve;
	}

	public void setUnidadVentaByIdUnve(UnidadVenta unidadVentaByIdUnve) {
		this.unidadVentaByIdUnve = unidadVentaByIdUnve;
	}

	public RelacionComercial getRelacionComercial() {
		return this.relacionComercial;
	}

	public void setRelacionComercial(RelacionComercial relacionComercial) {
		this.relacionComercial = relacionComercial;
	}

	public Sucursal getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Sucursal sucursal) {
		this.sucursal = sucursal;
	}

	public Long getNumeroDocumento() {
		return this.numeroDocumento;
	}

	public void setNumeroDocumento(Long numeroDocumento) {
		this.numeroDocumento = numeroDocumento;
	}

	public String getNumeroDefinitivo() {
		return this.numeroDefinitivo;
	}

	public void setNumeroDefinitivo(String numeroDefinitivo) {
		this.numeroDefinitivo = numeroDefinitivo;
	}

	public Double getValorTotal() {
		return this.valorTotal;
	}

	public void setValorTotal(Double valorTotal) {
		this.valorTotal = valorTotal;
	}

	public Date getFechaDocumento() {
		return this.fechaDocumento;
	}

	public void setFechaDocumento(Date fechaDocumento) {
		this.fechaDocumento = fechaDocumento;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

	public Set<OrdenesDeCompra> getOrdenesDeCompras() {
		return this.ordenesDeCompras;
	}

	public void setOrdenesDeCompras(Set<OrdenesDeCompra> ordenesDeCompras) {
		this.ordenesDeCompras = ordenesDeCompras;
	}

	public Set<LogisticaReversiva> getLogisticaReversivasForDocumentoAutorizacion() {
		return this.logisticaReversivasForDocumentoAutorizacion;
	}

	public void setLogisticaReversivasForDocumentoAutorizacion(
			Set<LogisticaReversiva> logisticaReversivasForDocumentoAutorizacion) {
		this.logisticaReversivasForDocumentoAutorizacion = logisticaReversivasForDocumentoAutorizacion;
	}

	public Set<Pedido> getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set<Pedido> pedidos) {
		this.pedidos = pedidos;
	}

	public Set<DetalleVisita> getDetalleVisitas() {
		return this.detalleVisitas;
	}

	public void setDetalleVisitas(Set<DetalleVisita> detalleVisitas) {
		this.detalleVisitas = detalleVisitas;
	}

	public Set<Garantia> getGarantias() {
		return this.garantias;
	}

	public void setGarantias(Set<Garantia> garantias) {
		this.garantias = garantias;
	}

	public Set<RboDetalleFormasPago> getRboDetalleFormasPagos() {
		return this.rboDetalleFormasPagos;
	}

	public void setRboDetalleFormasPagos(
			Set<RboDetalleFormasPago> rboDetalleFormasPagos) {
		this.rboDetalleFormasPagos = rboDetalleFormasPagos;
	}

	public Set<Recibo> getRecibos() {
		return this.recibos;
	}

	public void setRecibos(Set<Recibo> recibos) {
		this.recibos = recibos;
	}

	public Set<RboDetalleDocumentos> getRboDetalleDocumentoses() {
		return this.rboDetalleDocumentoses;
	}

	public void setRboDetalleDocumentoses(
			Set<RboDetalleDocumentos> rboDetalleDocumentoses) {
		this.rboDetalleDocumentoses = rboDetalleDocumentoses;
	}

	public Set<ItemRotacion> getItemRotacions() {
		return this.itemRotacions;
	}

	public void setItemRotacions(Set<ItemRotacion> itemRotacions) {
		this.itemRotacions = itemRotacions;
	}

	public Set<LogisticaReversiva> getLogisticaReversivasForDocumentoSolicitud() {
		return this.logisticaReversivasForDocumentoSolicitud;
	}

	public void setLogisticaReversivasForDocumentoSolicitud(
			Set<LogisticaReversiva> logisticaReversivasForDocumentoSolicitud) {
		this.logisticaReversivasForDocumentoSolicitud = logisticaReversivasForDocumentoSolicitud;
	}

	public Set<LogisticaReversiva> getLogisticaReversivasForDocumentoRecoleccion() {
		return this.logisticaReversivasForDocumentoRecoleccion;
	}

	public void setLogisticaReversivasForDocumentoRecoleccion(
			Set<LogisticaReversiva> logisticaReversivasForDocumentoRecoleccion) {
		this.logisticaReversivasForDocumentoRecoleccion = logisticaReversivasForDocumentoRecoleccion;
	}

	public Set<Cartera> getCarteras() {
		return this.carteras;
	}

	public void setCarteras(Set<Cartera> carteras) {
		this.carteras = carteras;
	}

	public Set<MovimientoInventario> getMovimientoInventarios() {
		return this.movimientoInventarios;
	}

	public void setMovimientoInventarios(
			Set<MovimientoInventario> movimientoInventarios) {
		this.movimientoInventarios = movimientoInventarios;
	}

}
