package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Familia generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class Familia implements java.io.Serializable {

	private Long idFlia;
	private String codigo;
	private String descripcion;
	private String manejaPesos;
	private String manejaGalones;
	private String manejaUnidades;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;
	private Set<PresupuestoVentas> presupuestoVentases = new HashSet<PresupuestoVentas>(
			0);
	private Set<Grupo> grupos = new HashSet<Grupo>(0);

	public Familia() {
	}

	public Familia(Long idFlia, String codigo, Date fechaCreacion,
			String operCreador, Date fechaModificacion, String operModifica,
			String estadoRegistro) {
		this.idFlia = idFlia;
		this.codigo = codigo;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public Familia(Long idFlia, String codigo, String descripcion,
			String manejaPesos, String manejaGalones, String manejaUnidades,
			Date fechaCreacion, String operCreador, Date fechaModificacion,
			String operModifica, String estadoRegistro,
			Set<PresupuestoVentas> presupuestoVentases, Set<Grupo> grupos) {
		this.idFlia = idFlia;
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.manejaPesos = manejaPesos;
		this.manejaGalones = manejaGalones;
		this.manejaUnidades = manejaUnidades;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
		this.presupuestoVentases = presupuestoVentases;
		this.grupos = grupos;
	}

	public Long getIdFlia() {
		return this.idFlia;
	}

	public void setIdFlia(Long idFlia) {
		this.idFlia = idFlia;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getManejaPesos() {
		return this.manejaPesos;
	}

	public void setManejaPesos(String manejaPesos) {
		this.manejaPesos = manejaPesos;
	}

	public String getManejaGalones() {
		return this.manejaGalones;
	}

	public void setManejaGalones(String manejaGalones) {
		this.manejaGalones = manejaGalones;
	}

	public String getManejaUnidades() {
		return this.manejaUnidades;
	}

	public void setManejaUnidades(String manejaUnidades) {
		this.manejaUnidades = manejaUnidades;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

	public Set<PresupuestoVentas> getPresupuestoVentases() {
		return this.presupuestoVentases;
	}

	public void setPresupuestoVentases(
			Set<PresupuestoVentas> presupuestoVentases) {
		this.presupuestoVentases = presupuestoVentases;
	}

	public Set<Grupo> getGrupos() {
		return this.grupos;
	}

	public void setGrupos(Set<Grupo> grupos) {
		this.grupos = grupos;
	}

}
