package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FrecuenciaVisita generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class FrecuenciaVisita implements java.io.Serializable {

	private Long idFrvi;
	private String codigo;
	private String descripcion;
	private Long frecuencia;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;
	private Set<ProgramacionVisitas> programacionVisitases = new HashSet<ProgramacionVisitas>(
			0);
	private Set<FrecuenciaSemana> frecuenciaSemanas = new HashSet<FrecuenciaSemana>(
			0);

	public FrecuenciaVisita() {
	}

	public FrecuenciaVisita(Long idFrvi, String codigo, Date fechaCreacion,
			String operCreador, Date fechaModificacion, String operModifica,
			String estadoRegistro) {
		this.idFrvi = idFrvi;
		this.codigo = codigo;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public FrecuenciaVisita(Long idFrvi, String codigo, String descripcion,
			Long frecuencia, Date fechaCreacion, String operCreador,
			Date fechaModificacion, String operModifica, String estadoRegistro,
			Set<ProgramacionVisitas> programacionVisitases,
			Set<FrecuenciaSemana> frecuenciaSemanas) {
		this.idFrvi = idFrvi;
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.frecuencia = frecuencia;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
		this.programacionVisitases = programacionVisitases;
		this.frecuenciaSemanas = frecuenciaSemanas;
	}

	public Long getIdFrvi() {
		return this.idFrvi;
	}

	public void setIdFrvi(Long idFrvi) {
		this.idFrvi = idFrvi;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Long getFrecuencia() {
		return this.frecuencia;
	}

	public void setFrecuencia(Long frecuencia) {
		this.frecuencia = frecuencia;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

	public Set<ProgramacionVisitas> getProgramacionVisitases() {
		return this.programacionVisitases;
	}

	public void setProgramacionVisitases(
			Set<ProgramacionVisitas> programacionVisitases) {
		this.programacionVisitases = programacionVisitases;
	}

	public Set<FrecuenciaSemana> getFrecuenciaSemanas() {
		return this.frecuenciaSemanas;
	}

	public void setFrecuenciaSemanas(Set<FrecuenciaSemana> frecuenciaSemanas) {
		this.frecuenciaSemanas = frecuenciaSemanas;
	}

}
