package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LogisticaReversiva generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class LogisticaReversiva implements java.io.Serializable {

	private Long idLore;
	private Documento documentoByDocumentoRecoleccion;
	private RutaRelacionComercial rutaRelacionComercial;
	private Documento documentoByDocumentoAutorizacion;
	private Documento documentoByDocumentoSolicitud;
	private Date fechaSolicitud;
	private Date fechaOrdenada;
	private Date fechaRecibida;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;
	private Set<ItemLogisticaReversiva> itemLogisticaReversivas = new HashSet<ItemLogisticaReversiva>(
			0);

	public LogisticaReversiva() {
	}

	public LogisticaReversiva(Long idLore,
			Documento documentoByDocumentoSolicitud, Date fechaCreacion,
			String operCreador, Date fechaModificacion, String operModifica,
			String estadoRegistro) {
		this.idLore = idLore;
		this.documentoByDocumentoSolicitud = documentoByDocumentoSolicitud;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public LogisticaReversiva(Long idLore,
			Documento documentoByDocumentoRecoleccion,
			RutaRelacionComercial rutaRelacionComercial,
			Documento documentoByDocumentoAutorizacion,
			Documento documentoByDocumentoSolicitud, Date fechaSolicitud,
			Date fechaOrdenada, Date fechaRecibida, Date fechaCreacion,
			String operCreador, Date fechaModificacion, String operModifica,
			String estadoRegistro,
			Set<ItemLogisticaReversiva> itemLogisticaReversivas) {
		this.idLore = idLore;
		this.documentoByDocumentoRecoleccion = documentoByDocumentoRecoleccion;
		this.rutaRelacionComercial = rutaRelacionComercial;
		this.documentoByDocumentoAutorizacion = documentoByDocumentoAutorizacion;
		this.documentoByDocumentoSolicitud = documentoByDocumentoSolicitud;
		this.fechaSolicitud = fechaSolicitud;
		this.fechaOrdenada = fechaOrdenada;
		this.fechaRecibida = fechaRecibida;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
		this.itemLogisticaReversivas = itemLogisticaReversivas;
	}

	public Long getIdLore() {
		return this.idLore;
	}

	public void setIdLore(Long idLore) {
		this.idLore = idLore;
	}

	public Documento getDocumentoByDocumentoRecoleccion() {
		return this.documentoByDocumentoRecoleccion;
	}

	public void setDocumentoByDocumentoRecoleccion(
			Documento documentoByDocumentoRecoleccion) {
		this.documentoByDocumentoRecoleccion = documentoByDocumentoRecoleccion;
	}

	public RutaRelacionComercial getRutaRelacionComercial() {
		return this.rutaRelacionComercial;
	}

	public void setRutaRelacionComercial(
			RutaRelacionComercial rutaRelacionComercial) {
		this.rutaRelacionComercial = rutaRelacionComercial;
	}

	public Documento getDocumentoByDocumentoAutorizacion() {
		return this.documentoByDocumentoAutorizacion;
	}

	public void setDocumentoByDocumentoAutorizacion(
			Documento documentoByDocumentoAutorizacion) {
		this.documentoByDocumentoAutorizacion = documentoByDocumentoAutorizacion;
	}

	public Documento getDocumentoByDocumentoSolicitud() {
		return this.documentoByDocumentoSolicitud;
	}

	public void setDocumentoByDocumentoSolicitud(
			Documento documentoByDocumentoSolicitud) {
		this.documentoByDocumentoSolicitud = documentoByDocumentoSolicitud;
	}

	public Date getFechaSolicitud() {
		return this.fechaSolicitud;
	}

	public void setFechaSolicitud(Date fechaSolicitud) {
		this.fechaSolicitud = fechaSolicitud;
	}

	public Date getFechaOrdenada() {
		return this.fechaOrdenada;
	}

	public void setFechaOrdenada(Date fechaOrdenada) {
		this.fechaOrdenada = fechaOrdenada;
	}

	public Date getFechaRecibida() {
		return this.fechaRecibida;
	}

	public void setFechaRecibida(Date fechaRecibida) {
		this.fechaRecibida = fechaRecibida;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

	public Set<ItemLogisticaReversiva> getItemLogisticaReversivas() {
		return this.itemLogisticaReversivas;
	}

	public void setItemLogisticaReversivas(
			Set<ItemLogisticaReversiva> itemLogisticaReversivas) {
		this.itemLogisticaReversivas = itemLogisticaReversivas;
	}

}
