package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * OrdenesDeCompra generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class OrdenesDeCompra implements java.io.Serializable {

	private Long idOrdc;
	private Referencia referencia;
	private Sucursal sucursal;
	private Documento documento;
	private Persona persona;
	private Empresa empresa;
	private Long numeroPedido;
	private Date fechaPedido;
	private Long cantidadPedida;
	private Double precioUnitarioPedido;
	private Double porcentajeDescuento;
	private Double iva;
	private String numeroFactura;
	private Long cantidadRecibido;
	private Double precioUnitarioRecibdo;
	private Date fechaEntrega;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;
	private Date fechaRecibido;

	public OrdenesDeCompra() {
	}

	public OrdenesDeCompra(Long idOrdc, Referencia referencia,
			Documento documento, Date fechaCreacion, String operCreador,
			Date fechaModificacion, String operModifica, String estadoRegistro) {
		this.idOrdc = idOrdc;
		this.referencia = referencia;
		this.documento = documento;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public OrdenesDeCompra(Long idOrdc, Referencia referencia,
			Sucursal sucursal, Documento documento, Persona persona,
			Empresa empresa, Long numeroPedido, Date fechaPedido,
			Long cantidadPedida, Double precioUnitarioPedido,
			Double porcentajeDescuento, Double iva, String numeroFactura,
			Long cantidadRecibido, Double precioUnitarioRecibdo,
			Date fechaEntrega, Date fechaCreacion, String operCreador,
			Date fechaModificacion, String operModifica, String estadoRegistro,
			Date fechaRecibido) {
		this.idOrdc = idOrdc;
		this.referencia = referencia;
		this.sucursal = sucursal;
		this.documento = documento;
		this.persona = persona;
		this.empresa = empresa;
		this.numeroPedido = numeroPedido;
		this.fechaPedido = fechaPedido;
		this.cantidadPedida = cantidadPedida;
		this.precioUnitarioPedido = precioUnitarioPedido;
		this.porcentajeDescuento = porcentajeDescuento;
		this.iva = iva;
		this.numeroFactura = numeroFactura;
		this.cantidadRecibido = cantidadRecibido;
		this.precioUnitarioRecibdo = precioUnitarioRecibdo;
		this.fechaEntrega = fechaEntrega;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
		this.fechaRecibido = fechaRecibido;
	}

	public Long getIdOrdc() {
		return this.idOrdc;
	}

	public void setIdOrdc(Long idOrdc) {
		this.idOrdc = idOrdc;
	}

	public Referencia getReferencia() {
		return this.referencia;
	}

	public void setReferencia(Referencia referencia) {
		this.referencia = referencia;
	}

	public Sucursal getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Sucursal sucursal) {
		this.sucursal = sucursal;
	}

	public Documento getDocumento() {
		return this.documento;
	}

	public void setDocumento(Documento documento) {
		this.documento = documento;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	public Long getNumeroPedido() {
		return this.numeroPedido;
	}

	public void setNumeroPedido(Long numeroPedido) {
		this.numeroPedido = numeroPedido;
	}

	public Date getFechaPedido() {
		return this.fechaPedido;
	}

	public void setFechaPedido(Date fechaPedido) {
		this.fechaPedido = fechaPedido;
	}

	public Long getCantidadPedida() {
		return this.cantidadPedida;
	}

	public void setCantidadPedida(Long cantidadPedida) {
		this.cantidadPedida = cantidadPedida;
	}

	public Double getPrecioUnitarioPedido() {
		return this.precioUnitarioPedido;
	}

	public void setPrecioUnitarioPedido(Double precioUnitarioPedido) {
		this.precioUnitarioPedido = precioUnitarioPedido;
	}

	public Double getPorcentajeDescuento() {
		return this.porcentajeDescuento;
	}

	public void setPorcentajeDescuento(Double porcentajeDescuento) {
		this.porcentajeDescuento = porcentajeDescuento;
	}

	public Double getIva() {
		return this.iva;
	}

	public void setIva(Double iva) {
		this.iva = iva;
	}

	public String getNumeroFactura() {
		return this.numeroFactura;
	}

	public void setNumeroFactura(String numeroFactura) {
		this.numeroFactura = numeroFactura;
	}

	public Long getCantidadRecibido() {
		return this.cantidadRecibido;
	}

	public void setCantidadRecibido(Long cantidadRecibido) {
		this.cantidadRecibido = cantidadRecibido;
	}

	public Double getPrecioUnitarioRecibdo() {
		return this.precioUnitarioRecibdo;
	}

	public void setPrecioUnitarioRecibdo(Double precioUnitarioRecibdo) {
		this.precioUnitarioRecibdo = precioUnitarioRecibdo;
	}

	public Date getFechaEntrega() {
		return this.fechaEntrega;
	}

	public void setFechaEntrega(Date fechaEntrega) {
		this.fechaEntrega = fechaEntrega;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

	public Date getFechaRecibido() {
		return this.fechaRecibido;
	}

	public void setFechaRecibido(Date fechaRecibido) {
		this.fechaRecibido = fechaRecibido;
	}

}
