package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * Pedido generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class Pedido implements java.io.Serializable {

	private Long idPddo;
	private Documento documento;
	private Referencia referencia;
	private Long numeroPedido;
	private String clasePedido;
	private String estadoPedido;
	private Date fechaPedido;
	private Date fechaDeseada;
	private Double precioVenta;
	private Double costoVenta;
	private Double porcentajeDescuento;
	private Double cantidadPedidas;
	private Double cantidadAdicionadas;
	private Double cantidadCanceladas;
	private Double cantidadOrdenada;
	private Double cantidadDespRecibir;
	private String urgencia;
	private String ordenDespacho;
	private String observacion;
	private String horaPedido;
	private Long numeroFactura;
	private Date fechaFactura;
	private Double existenciaAnterior;
	private String condicionPago;
	private String estadoSysgol;
	private String precioEspecial;
	private String comprometida;
	private Double cantidadComprometida;
	private String espacios;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;

	public Pedido() {
	}

	public Pedido(Long idPddo, Documento documento, Referencia referencia,
			Date fechaCreacion, String operCreador, Date fechaModificacion,
			String operModifica, String estadoRegistro) {
		this.idPddo = idPddo;
		this.documento = documento;
		this.referencia = referencia;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public Pedido(Long idPddo, Documento documento, Referencia referencia,
			Long numeroPedido, String clasePedido, String estadoPedido,
			Date fechaPedido, Date fechaDeseada, Double precioVenta,
			Double costoVenta, Double porcentajeDescuento,
			Double cantidadPedidas, Double cantidadAdicionadas,
			Double cantidadCanceladas, Double cantidadOrdenada,
			Double cantidadDespRecibir, String urgencia, String ordenDespacho,
			String observacion, String horaPedido, Long numeroFactura,
			Date fechaFactura, Double existenciaAnterior, String condicionPago,
			String estadoSysgol, String precioEspecial, String comprometida,
			Double cantidadComprometida, String espacios, Date fechaCreacion,
			String operCreador, Date fechaModificacion, String operModifica,
			String estadoRegistro) {
		this.idPddo = idPddo;
		this.documento = documento;
		this.referencia = referencia;
		this.numeroPedido = numeroPedido;
		this.clasePedido = clasePedido;
		this.estadoPedido = estadoPedido;
		this.fechaPedido = fechaPedido;
		this.fechaDeseada = fechaDeseada;
		this.precioVenta = precioVenta;
		this.costoVenta = costoVenta;
		this.porcentajeDescuento = porcentajeDescuento;
		this.cantidadPedidas = cantidadPedidas;
		this.cantidadAdicionadas = cantidadAdicionadas;
		this.cantidadCanceladas = cantidadCanceladas;
		this.cantidadOrdenada = cantidadOrdenada;
		this.cantidadDespRecibir = cantidadDespRecibir;
		this.urgencia = urgencia;
		this.ordenDespacho = ordenDespacho;
		this.observacion = observacion;
		this.horaPedido = horaPedido;
		this.numeroFactura = numeroFactura;
		this.fechaFactura = fechaFactura;
		this.existenciaAnterior = existenciaAnterior;
		this.condicionPago = condicionPago;
		this.estadoSysgol = estadoSysgol;
		this.precioEspecial = precioEspecial;
		this.comprometida = comprometida;
		this.cantidadComprometida = cantidadComprometida;
		this.espacios = espacios;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public Long getIdPddo() {
		return this.idPddo;
	}

	public void setIdPddo(Long idPddo) {
		this.idPddo = idPddo;
	}

	public Documento getDocumento() {
		return this.documento;
	}

	public void setDocumento(Documento documento) {
		this.documento = documento;
	}

	public Referencia getReferencia() {
		return this.referencia;
	}

	public void setReferencia(Referencia referencia) {
		this.referencia = referencia;
	}

	public Long getNumeroPedido() {
		return this.numeroPedido;
	}

	public void setNumeroPedido(Long numeroPedido) {
		this.numeroPedido = numeroPedido;
	}

	public String getClasePedido() {
		return this.clasePedido;
	}

	public void setClasePedido(String clasePedido) {
		this.clasePedido = clasePedido;
	}

	public String getEstadoPedido() {
		return this.estadoPedido;
	}

	public void setEstadoPedido(String estadoPedido) {
		this.estadoPedido = estadoPedido;
	}

	public Date getFechaPedido() {
		return this.fechaPedido;
	}

	public void setFechaPedido(Date fechaPedido) {
		this.fechaPedido = fechaPedido;
	}

	public Date getFechaDeseada() {
		return this.fechaDeseada;
	}

	public void setFechaDeseada(Date fechaDeseada) {
		this.fechaDeseada = fechaDeseada;
	}

	public Double getPrecioVenta() {
		return this.precioVenta;
	}

	public void setPrecioVenta(Double precioVenta) {
		this.precioVenta = precioVenta;
	}

	public Double getCostoVenta() {
		return this.costoVenta;
	}

	public void setCostoVenta(Double costoVenta) {
		this.costoVenta = costoVenta;
	}

	public Double getPorcentajeDescuento() {
		return this.porcentajeDescuento;
	}

	public void setPorcentajeDescuento(Double porcentajeDescuento) {
		this.porcentajeDescuento = porcentajeDescuento;
	}

	public Double getCantidadPedidas() {
		return this.cantidadPedidas;
	}

	public void setCantidadPedidas(Double cantidadPedidas) {
		this.cantidadPedidas = cantidadPedidas;
	}

	public Double getCantidadAdicionadas() {
		return this.cantidadAdicionadas;
	}

	public void setCantidadAdicionadas(Double cantidadAdicionadas) {
		this.cantidadAdicionadas = cantidadAdicionadas;
	}

	public Double getCantidadCanceladas() {
		return this.cantidadCanceladas;
	}

	public void setCantidadCanceladas(Double cantidadCanceladas) {
		this.cantidadCanceladas = cantidadCanceladas;
	}

	public Double getCantidadOrdenada() {
		return this.cantidadOrdenada;
	}

	public void setCantidadOrdenada(Double cantidadOrdenada) {
		this.cantidadOrdenada = cantidadOrdenada;
	}

	public Double getCantidadDespRecibir() {
		return this.cantidadDespRecibir;
	}

	public void setCantidadDespRecibir(Double cantidadDespRecibir) {
		this.cantidadDespRecibir = cantidadDespRecibir;
	}

	public String getUrgencia() {
		return this.urgencia;
	}

	public void setUrgencia(String urgencia) {
		this.urgencia = urgencia;
	}

	public String getOrdenDespacho() {
		return this.ordenDespacho;
	}

	public void setOrdenDespacho(String ordenDespacho) {
		this.ordenDespacho = ordenDespacho;
	}

	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	public String getHoraPedido() {
		return this.horaPedido;
	}

	public void setHoraPedido(String horaPedido) {
		this.horaPedido = horaPedido;
	}

	public Long getNumeroFactura() {
		return this.numeroFactura;
	}

	public void setNumeroFactura(Long numeroFactura) {
		this.numeroFactura = numeroFactura;
	}

	public Date getFechaFactura() {
		return this.fechaFactura;
	}

	public void setFechaFactura(Date fechaFactura) {
		this.fechaFactura = fechaFactura;
	}

	public Double getExistenciaAnterior() {
		return this.existenciaAnterior;
	}

	public void setExistenciaAnterior(Double existenciaAnterior) {
		this.existenciaAnterior = existenciaAnterior;
	}

	public String getCondicionPago() {
		return this.condicionPago;
	}

	public void setCondicionPago(String condicionPago) {
		this.condicionPago = condicionPago;
	}

	public String getEstadoSysgol() {
		return this.estadoSysgol;
	}

	public void setEstadoSysgol(String estadoSysgol) {
		this.estadoSysgol = estadoSysgol;
	}

	public String getPrecioEspecial() {
		return this.precioEspecial;
	}

	public void setPrecioEspecial(String precioEspecial) {
		this.precioEspecial = precioEspecial;
	}

	public String getComprometida() {
		return this.comprometida;
	}

	public void setComprometida(String comprometida) {
		this.comprometida = comprometida;
	}

	public Double getCantidadComprometida() {
		return this.cantidadComprometida;
	}

	public void setCantidadComprometida(Double cantidadComprometida) {
		this.cantidadComprometida = cantidadComprometida;
	}

	public String getEspacios() {
		return this.espacios;
	}

	public void setEspacios(String espacios) {
		this.espacios = espacios;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

}
