package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * PresupuestoVentas generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class PresupuestoVentas implements java.io.Serializable {

	private Long idPven;
	private Familia familia;
	private UnidadVenta unidadVenta;
	private Double valorPresupuesto;
	private Double cantidadPresupuesto;
	private Long ano;
	private Long mes;
	private String canal;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;

	public PresupuestoVentas() {
	}

	public PresupuestoVentas(Long idPven, Familia familia,
			UnidadVenta unidadVenta, Date fechaCreacion, String operCreador,
			Date fechaModificacion, String operModifica, String estadoRegistro) {
		this.idPven = idPven;
		this.familia = familia;
		this.unidadVenta = unidadVenta;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public PresupuestoVentas(Long idPven, Familia familia,
			UnidadVenta unidadVenta, Double valorPresupuesto,
			Double cantidadPresupuesto, Long ano, Long mes, String canal,
			Date fechaCreacion, String operCreador, Date fechaModificacion,
			String operModifica, String estadoRegistro) {
		this.idPven = idPven;
		this.familia = familia;
		this.unidadVenta = unidadVenta;
		this.valorPresupuesto = valorPresupuesto;
		this.cantidadPresupuesto = cantidadPresupuesto;
		this.ano = ano;
		this.mes = mes;
		this.canal = canal;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public Long getIdPven() {
		return this.idPven;
	}

	public void setIdPven(Long idPven) {
		this.idPven = idPven;
	}

	public Familia getFamilia() {
		return this.familia;
	}

	public void setFamilia(Familia familia) {
		this.familia = familia;
	}

	public UnidadVenta getUnidadVenta() {
		return this.unidadVenta;
	}

	public void setUnidadVenta(UnidadVenta unidadVenta) {
		this.unidadVenta = unidadVenta;
	}

	public Double getValorPresupuesto() {
		return this.valorPresupuesto;
	}

	public void setValorPresupuesto(Double valorPresupuesto) {
		this.valorPresupuesto = valorPresupuesto;
	}

	public Double getCantidadPresupuesto() {
		return this.cantidadPresupuesto;
	}

	public void setCantidadPresupuesto(Double cantidadPresupuesto) {
		this.cantidadPresupuesto = cantidadPresupuesto;
	}

	public Long getAno() {
		return this.ano;
	}

	public void setAno(Long ano) {
		this.ano = ano;
	}

	public Long getMes() {
		return this.mes;
	}

	public void setMes(Long mes) {
		this.mes = mes;
	}

	public String getCanal() {
		return this.canal;
	}

	public void setCanal(String canal) {
		this.canal = canal;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

}
