package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProgramacionVisitas generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class ProgramacionVisitas implements java.io.Serializable {

	private Long idPrvi;
	private DiasSemana diasSemana;
	private FrecuenciaVisita frecuenciaVisita;
	private AtencionVendedor atencionVendedor;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;
	private Set<Visita> visitas = new HashSet<Visita>(0);
	private Set<SolicitudCambio> solicitudCambios = new HashSet<SolicitudCambio>(
			0);

	public ProgramacionVisitas() {
	}

	public ProgramacionVisitas(Long idPrvi, DiasSemana diasSemana,
			FrecuenciaVisita frecuenciaVisita,
			AtencionVendedor atencionVendedor, Date fechaCreacion,
			String operCreador, Date fechaModificacion, String operModifica,
			String estadoRegistro) {
		this.idPrvi = idPrvi;
		this.diasSemana = diasSemana;
		this.frecuenciaVisita = frecuenciaVisita;
		this.atencionVendedor = atencionVendedor;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public ProgramacionVisitas(Long idPrvi, DiasSemana diasSemana,
			FrecuenciaVisita frecuenciaVisita,
			AtencionVendedor atencionVendedor, Date fechaCreacion,
			String operCreador, Date fechaModificacion, String operModifica,
			String estadoRegistro, Set<Visita> visitas,
			Set<SolicitudCambio> solicitudCambios) {
		this.idPrvi = idPrvi;
		this.diasSemana = diasSemana;
		this.frecuenciaVisita = frecuenciaVisita;
		this.atencionVendedor = atencionVendedor;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
		this.visitas = visitas;
		this.solicitudCambios = solicitudCambios;
	}

	public Long getIdPrvi() {
		return this.idPrvi;
	}

	public void setIdPrvi(Long idPrvi) {
		this.idPrvi = idPrvi;
	}

	public DiasSemana getDiasSemana() {
		return this.diasSemana;
	}

	public void setDiasSemana(DiasSemana diasSemana) {
		this.diasSemana = diasSemana;
	}

	public FrecuenciaVisita getFrecuenciaVisita() {
		return this.frecuenciaVisita;
	}

	public void setFrecuenciaVisita(FrecuenciaVisita frecuenciaVisita) {
		this.frecuenciaVisita = frecuenciaVisita;
	}

	public AtencionVendedor getAtencionVendedor() {
		return this.atencionVendedor;
	}

	public void setAtencionVendedor(AtencionVendedor atencionVendedor) {
		this.atencionVendedor = atencionVendedor;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

	public Set<Visita> getVisitas() {
		return this.visitas;
	}

	public void setVisitas(Set<Visita> visitas) {
		this.visitas = visitas;
	}

	public Set<SolicitudCambio> getSolicitudCambios() {
		return this.solicitudCambios;
	}

	public void setSolicitudCambios(Set<SolicitudCambio> solicitudCambios) {
		this.solicitudCambios = solicitudCambios;
	}

}
