package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * RboDetalleDocumentos generated by Zathura powered by
 * Hibernate-tools(hbm2java)
 */
public class RboDetalleDocumentos implements java.io.Serializable {

	private Long idRddo;
	private Documento documento;
	private DistribucionCartera distribucionCartera;
	private Cartera cartera;
	private ConceptoRecibo conceptoRecibo;
	private Recibo recibo;
	private UnidadVenta unidadVenta;
	private Sucursal sucursal;
	private Long numeroAbono;
	private Double montoAbonado;
	private String debitoCredito;
	private String lineaFamilia;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;
	private Double valorDescuento;
	private Long numeroRegistro;
	private Set<Cruce> cruces = new HashSet<Cruce>(0);

	public RboDetalleDocumentos() {
	}

	public RboDetalleDocumentos(Long idRddo, ConceptoRecibo conceptoRecibo,
			Recibo recibo, String debitoCredito, Date fechaCreacion,
			String operCreador, Date fechaModificacion, String operModifica,
			String estadoRegistro) {
		this.idRddo = idRddo;
		this.conceptoRecibo = conceptoRecibo;
		this.recibo = recibo;
		this.debitoCredito = debitoCredito;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public RboDetalleDocumentos(Long idRddo, Documento documento,
			DistribucionCartera distribucionCartera, Cartera cartera,
			ConceptoRecibo conceptoRecibo, Recibo recibo,
			UnidadVenta unidadVenta, Sucursal sucursal, Long numeroAbono,
			Double montoAbonado, String debitoCredito, String lineaFamilia,
			Date fechaCreacion, String operCreador, Date fechaModificacion,
			String operModifica, String estadoRegistro, Double valorDescuento,
			Long numeroRegistro, Set<Cruce> cruces) {
		this.idRddo = idRddo;
		this.documento = documento;
		this.distribucionCartera = distribucionCartera;
		this.cartera = cartera;
		this.conceptoRecibo = conceptoRecibo;
		this.recibo = recibo;
		this.unidadVenta = unidadVenta;
		this.sucursal = sucursal;
		this.numeroAbono = numeroAbono;
		this.montoAbonado = montoAbonado;
		this.debitoCredito = debitoCredito;
		this.lineaFamilia = lineaFamilia;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
		this.valorDescuento = valorDescuento;
		this.numeroRegistro = numeroRegistro;
		this.cruces = cruces;
	}

	public Long getIdRddo() {
		return this.idRddo;
	}

	public void setIdRddo(Long idRddo) {
		this.idRddo = idRddo;
	}

	public Documento getDocumento() {
		return this.documento;
	}

	public void setDocumento(Documento documento) {
		this.documento = documento;
	}

	public DistribucionCartera getDistribucionCartera() {
		return this.distribucionCartera;
	}

	public void setDistribucionCartera(DistribucionCartera distribucionCartera) {
		this.distribucionCartera = distribucionCartera;
	}

	public Cartera getCartera() {
		return this.cartera;
	}

	public void setCartera(Cartera cartera) {
		this.cartera = cartera;
	}

	public ConceptoRecibo getConceptoRecibo() {
		return this.conceptoRecibo;
	}

	public void setConceptoRecibo(ConceptoRecibo conceptoRecibo) {
		this.conceptoRecibo = conceptoRecibo;
	}

	public Recibo getRecibo() {
		return this.recibo;
	}

	public void setRecibo(Recibo recibo) {
		this.recibo = recibo;
	}

	public UnidadVenta getUnidadVenta() {
		return this.unidadVenta;
	}

	public void setUnidadVenta(UnidadVenta unidadVenta) {
		this.unidadVenta = unidadVenta;
	}

	public Sucursal getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Sucursal sucursal) {
		this.sucursal = sucursal;
	}

	public Long getNumeroAbono() {
		return this.numeroAbono;
	}

	public void setNumeroAbono(Long numeroAbono) {
		this.numeroAbono = numeroAbono;
	}

	public Double getMontoAbonado() {
		return this.montoAbonado;
	}

	public void setMontoAbonado(Double montoAbonado) {
		this.montoAbonado = montoAbonado;
	}

	public String getDebitoCredito() {
		return this.debitoCredito;
	}

	public void setDebitoCredito(String debitoCredito) {
		this.debitoCredito = debitoCredito;
	}

	public String getLineaFamilia() {
		return this.lineaFamilia;
	}

	public void setLineaFamilia(String lineaFamilia) {
		this.lineaFamilia = lineaFamilia;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

	public Double getValorDescuento() {
		return this.valorDescuento;
	}

	public void setValorDescuento(Double valorDescuento) {
		this.valorDescuento = valorDescuento;
	}

	public Long getNumeroRegistro() {
		return this.numeroRegistro;
	}

	public void setNumeroRegistro(Long numeroRegistro) {
		this.numeroRegistro = numeroRegistro;
	}

	public Set<Cruce> getCruces() {
		return this.cruces;
	}

	public void setCruces(Set<Cruce> cruces) {
		this.cruces = cruces;
	}

}
