package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ClaveFabricacion generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class ClaveFabricacion implements java.io.Serializable {

	private Long idClfa;
	private String codigo;
	private Date fechaInicial;
	private Date fechaFinal;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;
	private Set<Garantia> garantias = new HashSet<Garantia>(0);
	private Set<ClavesParaRotar> clavesParaRotars = new HashSet<ClavesParaRotar>(
			0);
	private Set<ItemRotacion> itemRotacions = new HashSet<ItemRotacion>(0);

	public ClaveFabricacion() {
	}

	public ClaveFabricacion(Long idClfa, Date fechaInicial, Date fechaFinal,
			Date fechaCreacion, String operCreador, Date fechaModificacion,
			String operModifica, String estadoRegistro) {
		this.idClfa = idClfa;
		this.fechaInicial = fechaInicial;
		this.fechaFinal = fechaFinal;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public ClaveFabricacion(Long idClfa, String codigo, Date fechaInicial,
			Date fechaFinal, Date fechaCreacion, String operCreador,
			Date fechaModificacion, String operModifica, String estadoRegistro,
			Set<Garantia> garantias, Set<ClavesParaRotar> clavesParaRotars,
			Set<ItemRotacion> itemRotacions) {
		this.idClfa = idClfa;
		this.codigo = codigo;
		this.fechaInicial = fechaInicial;
		this.fechaFinal = fechaFinal;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
		this.garantias = garantias;
		this.clavesParaRotars = clavesParaRotars;
		this.itemRotacions = itemRotacions;
	}

	public Long getIdClfa() {
		return this.idClfa;
	}

	public void setIdClfa(Long idClfa) {
		this.idClfa = idClfa;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public Date getFechaInicial() {
		return this.fechaInicial;
	}

	public void setFechaInicial(Date fechaInicial) {
		this.fechaInicial = fechaInicial;
	}

	public Date getFechaFinal() {
		return this.fechaFinal;
	}

	public void setFechaFinal(Date fechaFinal) {
		this.fechaFinal = fechaFinal;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

	public Set<Garantia> getGarantias() {
		return this.garantias;
	}

	public void setGarantias(Set<Garantia> garantias) {
		this.garantias = garantias;
	}

	public Set<ClavesParaRotar> getClavesParaRotars() {
		return this.clavesParaRotars;
	}

	public void setClavesParaRotars(Set<ClavesParaRotar> clavesParaRotars) {
		this.clavesParaRotars = clavesParaRotars;
	}

	public Set<ItemRotacion> getItemRotacions() {
		return this.itemRotacions;
	}

	public void setItemRotacions(Set<ItemRotacion> itemRotacions) {
		this.itemRotacions = itemRotacions;
	}

}
