package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DescuentoFinanciero generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class DescuentoFinanciero implements java.io.Serializable {

	private Long idDefi;
	private Grupo grupo;
	private TipoFormaPago tipoFormaPago;
	private Long codigo;
	private String nombre;
	private Date fechaInicio;
	private Date fechaFinal;
	private Double porcentajeDescuento;
	private Long diaDesde;
	private Long diaHasta;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;
	private Set<Cruce> cruces = new HashSet<Cruce>(0);

	public DescuentoFinanciero() {
	}

	public DescuentoFinanciero(Long idDefi, Grupo grupo, Long codigo,
			Double porcentajeDescuento, Date fechaCreacion, String operCreador,
			Date fechaModificacion, String operModifica, String estadoRegistro) {
		this.idDefi = idDefi;
		this.grupo = grupo;
		this.codigo = codigo;
		this.porcentajeDescuento = porcentajeDescuento;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public DescuentoFinanciero(Long idDefi, Grupo grupo,
			TipoFormaPago tipoFormaPago, Long codigo, String nombre,
			Date fechaInicio, Date fechaFinal, Double porcentajeDescuento,
			Long diaDesde, Long diaHasta, Date fechaCreacion,
			String operCreador, Date fechaModificacion, String operModifica,
			String estadoRegistro, Set<Cruce> cruces) {
		this.idDefi = idDefi;
		this.grupo = grupo;
		this.tipoFormaPago = tipoFormaPago;
		this.codigo = codigo;
		this.nombre = nombre;
		this.fechaInicio = fechaInicio;
		this.fechaFinal = fechaFinal;
		this.porcentajeDescuento = porcentajeDescuento;
		this.diaDesde = diaDesde;
		this.diaHasta = diaHasta;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
		this.cruces = cruces;
	}

	public Long getIdDefi() {
		return this.idDefi;
	}

	public void setIdDefi(Long idDefi) {
		this.idDefi = idDefi;
	}

	public Grupo getGrupo() {
		return this.grupo;
	}

	public void setGrupo(Grupo grupo) {
		this.grupo = grupo;
	}

	public TipoFormaPago getTipoFormaPago() {
		return this.tipoFormaPago;
	}

	public void setTipoFormaPago(TipoFormaPago tipoFormaPago) {
		this.tipoFormaPago = tipoFormaPago;
	}

	public Long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Date getFechaFinal() {
		return this.fechaFinal;
	}

	public void setFechaFinal(Date fechaFinal) {
		this.fechaFinal = fechaFinal;
	}

	public Double getPorcentajeDescuento() {
		return this.porcentajeDescuento;
	}

	public void setPorcentajeDescuento(Double porcentajeDescuento) {
		this.porcentajeDescuento = porcentajeDescuento;
	}

	public Long getDiaDesde() {
		return this.diaDesde;
	}

	public void setDiaDesde(Long diaDesde) {
		this.diaDesde = diaDesde;
	}

	public Long getDiaHasta() {
		return this.diaHasta;
	}

	public void setDiaHasta(Long diaHasta) {
		this.diaHasta = diaHasta;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

	public Set<Cruce> getCruces() {
		return this.cruces;
	}

	public void setCruces(Set<Cruce> cruces) {
		this.cruces = cruces;
	}

}
