package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DivisionPolitica generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class DivisionPolitica implements java.io.Serializable {

	private Long idDipo;
	private TipoDivision tipoDivision;
	private DivisionPolitica divisionPolitica;
	private String nombre;
	private String codigoDian;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;
	private Set<Sucursal> sucursals = new HashSet<Sucursal>(0);
	private Set<Persona> personas = new HashSet<Persona>(0);
	private Set<Empresa> empresas = new HashSet<Empresa>(0);
	private Set<DivisionPolitica> divisionPoliticas = new HashSet<DivisionPolitica>(
			0);

	public DivisionPolitica() {
	}

	public DivisionPolitica(Long idDipo, TipoDivision tipoDivision,
			String nombre, Date fechaCreacion, String operCreador,
			Date fechaModificacion, String operModifica, String estadoRegistro) {
		this.idDipo = idDipo;
		this.tipoDivision = tipoDivision;
		this.nombre = nombre;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public DivisionPolitica(Long idDipo, TipoDivision tipoDivision,
			DivisionPolitica divisionPolitica, String nombre,
			String codigoDian, Date fechaCreacion, String operCreador,
			Date fechaModificacion, String operModifica, String estadoRegistro,
			Set<Sucursal> sucursals, Set<Persona> personas,
			Set<Empresa> empresas, Set<DivisionPolitica> divisionPoliticas) {
		this.idDipo = idDipo;
		this.tipoDivision = tipoDivision;
		this.divisionPolitica = divisionPolitica;
		this.nombre = nombre;
		this.codigoDian = codigoDian;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
		this.sucursals = sucursals;
		this.personas = personas;
		this.empresas = empresas;
		this.divisionPoliticas = divisionPoliticas;
	}

	public Long getIdDipo() {
		return this.idDipo;
	}

	public void setIdDipo(Long idDipo) {
		this.idDipo = idDipo;
	}

	public TipoDivision getTipoDivision() {
		return this.tipoDivision;
	}

	public void setTipoDivision(TipoDivision tipoDivision) {
		this.tipoDivision = tipoDivision;
	}

	public DivisionPolitica getDivisionPolitica() {
		return this.divisionPolitica;
	}

	public void setDivisionPolitica(DivisionPolitica divisionPolitica) {
		this.divisionPolitica = divisionPolitica;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCodigoDian() {
		return this.codigoDian;
	}

	public void setCodigoDian(String codigoDian) {
		this.codigoDian = codigoDian;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

	public Set<Sucursal> getSucursals() {
		return this.sucursals;
	}

	public void setSucursals(Set<Sucursal> sucursals) {
		this.sucursals = sucursals;
	}

	public Set<Persona> getPersonas() {
		return this.personas;
	}

	public void setPersonas(Set<Persona> personas) {
		this.personas = personas;
	}

	public Set<Empresa> getEmpresas() {
		return this.empresas;
	}

	public void setEmpresas(Set<Empresa> empresas) {
		this.empresas = empresas;
	}

	public Set<DivisionPolitica> getDivisionPoliticas() {
		return this.divisionPoliticas;
	}

	public void setDivisionPoliticas(Set<DivisionPolitica> divisionPoliticas) {
		this.divisionPoliticas = divisionPoliticas;
	}

}
