package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * PeriodoGarantia generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class PeriodoGarantia implements java.io.Serializable {

	private Long idPega;
	private Grupo grupo;
	private Long mesesParticular;
	private Long mesesPublico;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;

	public PeriodoGarantia() {
	}

	public PeriodoGarantia(Long idPega, Grupo grupo, Date fechaCreacion,
			String operCreador, Date fechaModificacion, String operModifica,
			String estadoRegistro) {
		this.idPega = idPega;
		this.grupo = grupo;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public PeriodoGarantia(Long idPega, Grupo grupo, Long mesesParticular,
			Long mesesPublico, Date fechaCreacion, String operCreador,
			Date fechaModificacion, String operModifica, String estadoRegistro) {
		this.idPega = idPega;
		this.grupo = grupo;
		this.mesesParticular = mesesParticular;
		this.mesesPublico = mesesPublico;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public Long getIdPega() {
		return this.idPega;
	}

	public void setIdPega(Long idPega) {
		this.idPega = idPega;
	}

	public Grupo getGrupo() {
		return this.grupo;
	}

	public void setGrupo(Grupo grupo) {
		this.grupo = grupo;
	}

	public Long getMesesParticular() {
		return this.mesesParticular;
	}

	public void setMesesParticular(Long mesesParticular) {
		this.mesesParticular = mesesParticular;
	}

	public Long getMesesPublico() {
		return this.mesesPublico;
	}

	public void setMesesPublico(Long mesesPublico) {
		this.mesesPublico = mesesPublico;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

}
