package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class Persona implements java.io.Serializable {

	private Long idPers;
	private DivisionPolitica divisionPolitica;
	private TipoIdentificacion tipoIdentificacion;
	private Long identificacion;
	private String primerNombre;
	private String segundoNombre;
	private String primerApellido;
	private String segundoApellido;
	private String direccion;
	private String telefono1;
	private String telefono2;
	private String apartadoAereo;
	private String email;
	private String digitoVerificacion;
	private Long estadoPersona;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;
	private Set<DescuentoComercial> descuentoComercials = new HashSet<DescuentoComercial>(
			0);
	private Set<OrdenesDeCompra> ordenesDeCompras = new HashSet<OrdenesDeCompra>(
			0);
	private Set<Cliente> clientes = new HashSet<Cliente>(0);
	private Set<Empresa> empresas = new HashSet<Empresa>(0);
	private Set<ListaPreciosEspeciales> listaPreciosEspecialeses = new HashSet<ListaPreciosEspeciales>(
			0);
	private Set<Proveedor> proveedors = new HashSet<Proveedor>(0);
	private Set<Vendedor> vendedors = new HashSet<Vendedor>(0);
	private Set<RelacionComercial> relacionComercials = new HashSet<RelacionComercial>(
			0);
	private Set<Sucursal> sucursals = new HashSet<Sucursal>(0);

	public Persona() {
	}

	public Persona(Long idPers, TipoIdentificacion tipoIdentificacion,
			Long identificacion, String primerNombre, Date fechaCreacion,
			String operCreador, Date fechaModificacion, String operModifica,
			String estadoRegistro) {
		this.idPers = idPers;
		this.tipoIdentificacion = tipoIdentificacion;
		this.identificacion = identificacion;
		this.primerNombre = primerNombre;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public Persona(Long idPers, DivisionPolitica divisionPolitica,
			TipoIdentificacion tipoIdentificacion, Long identificacion,
			String primerNombre, String segundoNombre, String primerApellido,
			String segundoApellido, String direccion, String telefono1,
			String telefono2, String apartadoAereo, String email,
			String digitoVerificacion, Long estadoPersona, Date fechaCreacion,
			String operCreador, Date fechaModificacion, String operModifica,
			String estadoRegistro, Set<DescuentoComercial> descuentoComercials,
			Set<OrdenesDeCompra> ordenesDeCompras, Set<Cliente> clientes,
			Set<Empresa> empresas,
			Set<ListaPreciosEspeciales> listaPreciosEspecialeses,
			Set<Proveedor> proveedors, Set<Vendedor> vendedors,
			Set<RelacionComercial> relacionComercials, Set<Sucursal> sucursals) {
		this.idPers = idPers;
		this.divisionPolitica = divisionPolitica;
		this.tipoIdentificacion = tipoIdentificacion;
		this.identificacion = identificacion;
		this.primerNombre = primerNombre;
		this.segundoNombre = segundoNombre;
		this.primerApellido = primerApellido;
		this.segundoApellido = segundoApellido;
		this.direccion = direccion;
		this.telefono1 = telefono1;
		this.telefono2 = telefono2;
		this.apartadoAereo = apartadoAereo;
		this.email = email;
		this.digitoVerificacion = digitoVerificacion;
		this.estadoPersona = estadoPersona;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
		this.descuentoComercials = descuentoComercials;
		this.ordenesDeCompras = ordenesDeCompras;
		this.clientes = clientes;
		this.empresas = empresas;
		this.listaPreciosEspecialeses = listaPreciosEspecialeses;
		this.proveedors = proveedors;
		this.vendedors = vendedors;
		this.relacionComercials = relacionComercials;
		this.sucursals = sucursals;
	}

	public Long getIdPers() {
		return this.idPers;
	}

	public void setIdPers(Long idPers) {
		this.idPers = idPers;
	}

	public DivisionPolitica getDivisionPolitica() {
		return this.divisionPolitica;
	}

	public void setDivisionPolitica(DivisionPolitica divisionPolitica) {
		this.divisionPolitica = divisionPolitica;
	}

	public TipoIdentificacion getTipoIdentificacion() {
		return this.tipoIdentificacion;
	}

	public void setTipoIdentificacion(TipoIdentificacion tipoIdentificacion) {
		this.tipoIdentificacion = tipoIdentificacion;
	}

	public Long getIdentificacion() {
		return this.identificacion;
	}

	public void setIdentificacion(Long identificacion) {
		this.identificacion = identificacion;
	}

	public String getPrimerNombre() {
		return this.primerNombre;
	}

	public void setPrimerNombre(String primerNombre) {
		this.primerNombre = primerNombre;
	}

	public String getSegundoNombre() {
		return this.segundoNombre;
	}

	public void setSegundoNombre(String segundoNombre) {
		this.segundoNombre = segundoNombre;
	}

	public String getPrimerApellido() {
		return this.primerApellido;
	}

	public void setPrimerApellido(String primerApellido) {
		this.primerApellido = primerApellido;
	}

	public String getSegundoApellido() {
		return this.segundoApellido;
	}

	public void setSegundoApellido(String segundoApellido) {
		this.segundoApellido = segundoApellido;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTelefono1() {
		return this.telefono1;
	}

	public void setTelefono1(String telefono1) {
		this.telefono1 = telefono1;
	}

	public String getTelefono2() {
		return this.telefono2;
	}

	public void setTelefono2(String telefono2) {
		this.telefono2 = telefono2;
	}

	public String getApartadoAereo() {
		return this.apartadoAereo;
	}

	public void setApartadoAereo(String apartadoAereo) {
		this.apartadoAereo = apartadoAereo;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getDigitoVerificacion() {
		return this.digitoVerificacion;
	}

	public void setDigitoVerificacion(String digitoVerificacion) {
		this.digitoVerificacion = digitoVerificacion;
	}

	public Long getEstadoPersona() {
		return this.estadoPersona;
	}

	public void setEstadoPersona(Long estadoPersona) {
		this.estadoPersona = estadoPersona;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

	public Set<DescuentoComercial> getDescuentoComercials() {
		return this.descuentoComercials;
	}

	public void setDescuentoComercials(
			Set<DescuentoComercial> descuentoComercials) {
		this.descuentoComercials = descuentoComercials;
	}

	public Set<OrdenesDeCompra> getOrdenesDeCompras() {
		return this.ordenesDeCompras;
	}

	public void setOrdenesDeCompras(Set<OrdenesDeCompra> ordenesDeCompras) {
		this.ordenesDeCompras = ordenesDeCompras;
	}

	public Set<Cliente> getClientes() {
		return this.clientes;
	}

	public void setClientes(Set<Cliente> clientes) {
		this.clientes = clientes;
	}

	public Set<Empresa> getEmpresas() {
		return this.empresas;
	}

	public void setEmpresas(Set<Empresa> empresas) {
		this.empresas = empresas;
	}

	public Set<ListaPreciosEspeciales> getListaPreciosEspecialeses() {
		return this.listaPreciosEspecialeses;
	}

	public void setListaPreciosEspecialeses(
			Set<ListaPreciosEspeciales> listaPreciosEspecialeses) {
		this.listaPreciosEspecialeses = listaPreciosEspecialeses;
	}

	public Set<Proveedor> getProveedors() {
		return this.proveedors;
	}

	public void setProveedors(Set<Proveedor> proveedors) {
		this.proveedors = proveedors;
	}

	public Set<Vendedor> getVendedors() {
		return this.vendedors;
	}

	public void setVendedors(Set<Vendedor> vendedors) {
		this.vendedors = vendedors;
	}

	public Set<RelacionComercial> getRelacionComercials() {
		return this.relacionComercials;
	}

	public void setRelacionComercials(Set<RelacionComercial> relacionComercials) {
		this.relacionComercials = relacionComercials;
	}

	public Set<Sucursal> getSucursals() {
		return this.sucursals;
	}

	public void setSucursals(Set<Sucursal> sucursals) {
		this.sucursals = sucursals;
	}

}
