package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * PresupuestoCartera generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class PresupuestoCartera implements java.io.Serializable {

	private Long idPrca;
	private UnidadVenta unidadVenta;
	private Double valorPresupuesto;
	private Long ano;
	private Long mes;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;

	public PresupuestoCartera() {
	}

	public PresupuestoCartera(Long idPrca, UnidadVenta unidadVenta,
			Date fechaCreacion, String operCreador, Date fechaModificacion,
			String operModifica, String estadoRegistro) {
		this.idPrca = idPrca;
		this.unidadVenta = unidadVenta;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public PresupuestoCartera(Long idPrca, UnidadVenta unidadVenta,
			Double valorPresupuesto, Long ano, Long mes, Date fechaCreacion,
			String operCreador, Date fechaModificacion, String operModifica,
			String estadoRegistro) {
		this.idPrca = idPrca;
		this.unidadVenta = unidadVenta;
		this.valorPresupuesto = valorPresupuesto;
		this.ano = ano;
		this.mes = mes;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public Long getIdPrca() {
		return this.idPrca;
	}

	public void setIdPrca(Long idPrca) {
		this.idPrca = idPrca;
	}

	public UnidadVenta getUnidadVenta() {
		return this.unidadVenta;
	}

	public void setUnidadVenta(UnidadVenta unidadVenta) {
		this.unidadVenta = unidadVenta;
	}

	public Double getValorPresupuesto() {
		return this.valorPresupuesto;
	}

	public void setValorPresupuesto(Double valorPresupuesto) {
		this.valorPresupuesto = valorPresupuesto;
	}

	public Long getAno() {
		return this.ano;
	}

	public void setAno(Long ano) {
		this.ano = ano;
	}

	public Long getMes() {
		return this.mes;
	}

	public void setMes(Long mes) {
		this.mes = mes;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

}
