package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ReferenciaSucursal generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class ReferenciaSucursal implements java.io.Serializable {

	private Long idResu;
	private Referencia referencia;
	private Sucursal sucursal;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;
	private Set<SaldoInicialInventario> saldoInicialInventarios = new HashSet<SaldoInicialInventario>(
			0);
	private Set<MovimientoInventario> movimientoInventarios = new HashSet<MovimientoInventario>(
			0);

	public ReferenciaSucursal() {
	}

	public ReferenciaSucursal(Long idResu, Referencia referencia,
			Sucursal sucursal, Date fechaCreacion, String operCreador,
			Date fechaModificacion, String operModifica, String estadoRegistro) {
		this.idResu = idResu;
		this.referencia = referencia;
		this.sucursal = sucursal;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public ReferenciaSucursal(Long idResu, Referencia referencia,
			Sucursal sucursal, Date fechaCreacion, String operCreador,
			Date fechaModificacion, String operModifica, String estadoRegistro,
			Set<SaldoInicialInventario> saldoInicialInventarios,
			Set<MovimientoInventario> movimientoInventarios) {
		this.idResu = idResu;
		this.referencia = referencia;
		this.sucursal = sucursal;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
		this.saldoInicialInventarios = saldoInicialInventarios;
		this.movimientoInventarios = movimientoInventarios;
	}

	public Long getIdResu() {
		return this.idResu;
	}

	public void setIdResu(Long idResu) {
		this.idResu = idResu;
	}

	public Referencia getReferencia() {
		return this.referencia;
	}

	public void setReferencia(Referencia referencia) {
		this.referencia = referencia;
	}

	public Sucursal getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Sucursal sucursal) {
		this.sucursal = sucursal;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

	public Set<SaldoInicialInventario> getSaldoInicialInventarios() {
		return this.saldoInicialInventarios;
	}

	public void setSaldoInicialInventarios(
			Set<SaldoInicialInventario> saldoInicialInventarios) {
		this.saldoInicialInventarios = saldoInicialInventarios;
	}

	public Set<MovimientoInventario> getMovimientoInventarios() {
		return this.movimientoInventarios;
	}

	public void setMovimientoInventarios(
			Set<MovimientoInventario> movimientoInventarios) {
		this.movimientoInventarios = movimientoInventarios;
	}

}
