package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * RelacionComercial generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class RelacionComercial implements java.io.Serializable {

	private Long idReco;
	private Persona persona;
	private Sucursal sucursalBySucursalHija;
	private Sucursal sucursalBySucursalPadre;
	private Empresa empresa;
	private String liquidaIva;
	private Double limiteCredito;
	private String observacion;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;
	private Set<AtencionVendedor> atencionVendedors = new HashSet<AtencionVendedor>(
			0);
	private Set<Documento> documentos = new HashSet<Documento>(0);

	public RelacionComercial() {
	}

	public RelacionComercial(Long idReco, Sucursal sucursalBySucursalPadre,
			Date fechaCreacion, String operCreador, Date fechaModificacion,
			String operModifica, String estadoRegistro) {
		this.idReco = idReco;
		this.sucursalBySucursalPadre = sucursalBySucursalPadre;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public RelacionComercial(Long idReco, Persona persona,
			Sucursal sucursalBySucursalHija, Sucursal sucursalBySucursalPadre,
			Empresa empresa, String liquidaIva, Double limiteCredito,
			String observacion, Date fechaCreacion, String operCreador,
			Date fechaModificacion, String operModifica, String estadoRegistro,
			Set<AtencionVendedor> atencionVendedors, Set<Documento> documentos) {
		this.idReco = idReco;
		this.persona = persona;
		this.sucursalBySucursalHija = sucursalBySucursalHija;
		this.sucursalBySucursalPadre = sucursalBySucursalPadre;
		this.empresa = empresa;
		this.liquidaIva = liquidaIva;
		this.limiteCredito = limiteCredito;
		this.observacion = observacion;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
		this.atencionVendedors = atencionVendedors;
		this.documentos = documentos;
	}

	public Long getIdReco() {
		return this.idReco;
	}

	public void setIdReco(Long idReco) {
		this.idReco = idReco;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public Sucursal getSucursalBySucursalHija() {
		return this.sucursalBySucursalHija;
	}

	public void setSucursalBySucursalHija(Sucursal sucursalBySucursalHija) {
		this.sucursalBySucursalHija = sucursalBySucursalHija;
	}

	public Sucursal getSucursalBySucursalPadre() {
		return this.sucursalBySucursalPadre;
	}

	public void setSucursalBySucursalPadre(Sucursal sucursalBySucursalPadre) {
		this.sucursalBySucursalPadre = sucursalBySucursalPadre;
	}

	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	public String getLiquidaIva() {
		return this.liquidaIva;
	}

	public void setLiquidaIva(String liquidaIva) {
		this.liquidaIva = liquidaIva;
	}

	public Double getLimiteCredito() {
		return this.limiteCredito;
	}

	public void setLimiteCredito(Double limiteCredito) {
		this.limiteCredito = limiteCredito;
	}

	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

	public Set<AtencionVendedor> getAtencionVendedors() {
		return this.atencionVendedors;
	}

	public void setAtencionVendedors(Set<AtencionVendedor> atencionVendedors) {
		this.atencionVendedors = atencionVendedors;
	}

	public Set<Documento> getDocumentos() {
		return this.documentos;
	}

	public void setDocumentos(Set<Documento> documentos) {
		this.documentos = documentos;
	}

}
