package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoFormaPago generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class TipoFormaPago implements java.io.Serializable {

	private Long idTfpa;
	private String codigo;
	private String descripcion;
	private Long manejaCheque;
	private Long manejaTarjeta;
	private Long exijeNumeroDocumento;
	private Long esPosfechado;
	private Long importaPda;
	private Long dsctoFechaDoc;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;
	private Set<RboDetalleFormasPago> rboDetalleFormasPagos = new HashSet<RboDetalleFormasPago>(
			0);
	private Set<DescuentoFinanciero> descuentoFinancieros = new HashSet<DescuentoFinanciero>(
			0);

	public TipoFormaPago() {
	}

	public TipoFormaPago(Long idTfpa, String codigo, String descripcion,
			Date fechaCreacion, String operCreador, Date fechaModificacion,
			String operModifica, String estadoRegistro) {
		this.idTfpa = idTfpa;
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public TipoFormaPago(Long idTfpa, String codigo, String descripcion,
			Long manejaCheque, Long manejaTarjeta, Long exijeNumeroDocumento,
			Long esPosfechado, Long importaPda, Long dsctoFechaDoc,
			Date fechaCreacion, String operCreador, Date fechaModificacion,
			String operModifica, String estadoRegistro,
			Set<RboDetalleFormasPago> rboDetalleFormasPagos,
			Set<DescuentoFinanciero> descuentoFinancieros) {
		this.idTfpa = idTfpa;
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.manejaCheque = manejaCheque;
		this.manejaTarjeta = manejaTarjeta;
		this.exijeNumeroDocumento = exijeNumeroDocumento;
		this.esPosfechado = esPosfechado;
		this.importaPda = importaPda;
		this.dsctoFechaDoc = dsctoFechaDoc;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
		this.rboDetalleFormasPagos = rboDetalleFormasPagos;
		this.descuentoFinancieros = descuentoFinancieros;
	}

	public Long getIdTfpa() {
		return this.idTfpa;
	}

	public void setIdTfpa(Long idTfpa) {
		this.idTfpa = idTfpa;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Long getManejaCheque() {
		return this.manejaCheque;
	}

	public void setManejaCheque(Long manejaCheque) {
		this.manejaCheque = manejaCheque;
	}

	public Long getManejaTarjeta() {
		return this.manejaTarjeta;
	}

	public void setManejaTarjeta(Long manejaTarjeta) {
		this.manejaTarjeta = manejaTarjeta;
	}

	public Long getExijeNumeroDocumento() {
		return this.exijeNumeroDocumento;
	}

	public void setExijeNumeroDocumento(Long exijeNumeroDocumento) {
		this.exijeNumeroDocumento = exijeNumeroDocumento;
	}

	public Long getEsPosfechado() {
		return this.esPosfechado;
	}

	public void setEsPosfechado(Long esPosfechado) {
		this.esPosfechado = esPosfechado;
	}

	public Long getImportaPda() {
		return this.importaPda;
	}

	public void setImportaPda(Long importaPda) {
		this.importaPda = importaPda;
	}

	public Long getDsctoFechaDoc() {
		return this.dsctoFechaDoc;
	}

	public void setDsctoFechaDoc(Long dsctoFechaDoc) {
		this.dsctoFechaDoc = dsctoFechaDoc;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

	public Set<RboDetalleFormasPago> getRboDetalleFormasPagos() {
		return this.rboDetalleFormasPagos;
	}

	public void setRboDetalleFormasPagos(
			Set<RboDetalleFormasPago> rboDetalleFormasPagos) {
		this.rboDetalleFormasPagos = rboDetalleFormasPagos;
	}

	public Set<DescuentoFinanciero> getDescuentoFinancieros() {
		return this.descuentoFinancieros;
	}

	public void setDescuentoFinancieros(
			Set<DescuentoFinanciero> descuentoFinancieros) {
		this.descuentoFinancieros = descuentoFinancieros;
	}

}
