package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoDocumento generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class TipoDocumento implements java.io.Serializable {

	private Long idTido;
	private String codigo;
	private String descripcion;
	private String afectaInventario;
	private String afectaCartea;
	private String signoInventario;
	private String signoCartera;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;
	private Set<Documento> documentos = new HashSet<Documento>(0);
	private Set<ConsecutivoDocumento> consecutivoDocumentos = new HashSet<ConsecutivoDocumento>(
			0);

	public TipoDocumento() {
	}

	public TipoDocumento(Long idTido, String afectaInventario,
			String afectaCartea, Date fechaCreacion, String operCreador,
			Date fechaModificacion, String operModifica, String estadoRegistro) {
		this.idTido = idTido;
		this.afectaInventario = afectaInventario;
		this.afectaCartea = afectaCartea;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public TipoDocumento(Long idTido, String codigo, String descripcion,
			String afectaInventario, String afectaCartea,
			String signoInventario, String signoCartera, Date fechaCreacion,
			String operCreador, Date fechaModificacion, String operModifica,
			String estadoRegistro, Set<Documento> documentos,
			Set<ConsecutivoDocumento> consecutivoDocumentos) {
		this.idTido = idTido;
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.afectaInventario = afectaInventario;
		this.afectaCartea = afectaCartea;
		this.signoInventario = signoInventario;
		this.signoCartera = signoCartera;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
		this.documentos = documentos;
		this.consecutivoDocumentos = consecutivoDocumentos;
	}

	public Long getIdTido() {
		return this.idTido;
	}

	public void setIdTido(Long idTido) {
		this.idTido = idTido;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getAfectaInventario() {
		return this.afectaInventario;
	}

	public void setAfectaInventario(String afectaInventario) {
		this.afectaInventario = afectaInventario;
	}

	public String getAfectaCartea() {
		return this.afectaCartea;
	}

	public void setAfectaCartea(String afectaCartea) {
		this.afectaCartea = afectaCartea;
	}

	public String getSignoInventario() {
		return this.signoInventario;
	}

	public void setSignoInventario(String signoInventario) {
		this.signoInventario = signoInventario;
	}

	public String getSignoCartera() {
		return this.signoCartera;
	}

	public void setSignoCartera(String signoCartera) {
		this.signoCartera = signoCartera;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

	public Set<Documento> getDocumentos() {
		return this.documentos;
	}

	public void setDocumentos(Set<Documento> documentos) {
		this.documentos = documentos;
	}

	public Set<ConsecutivoDocumento> getConsecutivoDocumentos() {
		return this.consecutivoDocumentos;
	}

	public void setConsecutivoDocumentos(
			Set<ConsecutivoDocumento> consecutivoDocumentos) {
		this.consecutivoDocumentos = consecutivoDocumentos;
	}

}
