package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Visita generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class Visita implements java.io.Serializable {

	private Long idVisi;
	private Causal causal;
	private ProgramacionAdicional programacionAdicional;
	private ProgramacionVisitas programacionVisitas;
	private String estadoVisita;
	private String observacion;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;
	private Set<DetalleVisita> detalleVisitas = new HashSet<DetalleVisita>(0);

	public Visita() {
	}

	public Visita(Long idVisi, String estadoVisita, Date fechaCreacion,
			String operCreador, Date fechaModificacion, String operModifica,
			String estadoRegistro) {
		this.idVisi = idVisi;
		this.estadoVisita = estadoVisita;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public Visita(Long idVisi, Causal causal,
			ProgramacionAdicional programacionAdicional,
			ProgramacionVisitas programacionVisitas, String estadoVisita,
			String observacion, Date fechaCreacion, String operCreador,
			Date fechaModificacion, String operModifica, String estadoRegistro,
			Set<DetalleVisita> detalleVisitas) {
		this.idVisi = idVisi;
		this.causal = causal;
		this.programacionAdicional = programacionAdicional;
		this.programacionVisitas = programacionVisitas;
		this.estadoVisita = estadoVisita;
		this.observacion = observacion;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
		this.detalleVisitas = detalleVisitas;
	}

	public Long getIdVisi() {
		return this.idVisi;
	}

	public void setIdVisi(Long idVisi) {
		this.idVisi = idVisi;
	}

	public Causal getCausal() {
		return this.causal;
	}

	public void setCausal(Causal causal) {
		this.causal = causal;
	}

	public ProgramacionAdicional getProgramacionAdicional() {
		return this.programacionAdicional;
	}

	public void setProgramacionAdicional(
			ProgramacionAdicional programacionAdicional) {
		this.programacionAdicional = programacionAdicional;
	}

	public ProgramacionVisitas getProgramacionVisitas() {
		return this.programacionVisitas;
	}

	public void setProgramacionVisitas(ProgramacionVisitas programacionVisitas) {
		this.programacionVisitas = programacionVisitas;
	}

	public String getEstadoVisita() {
		return this.estadoVisita;
	}

	public void setEstadoVisita(String estadoVisita) {
		this.estadoVisita = estadoVisita;
	}

	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

	public Set<DetalleVisita> getDetalleVisitas() {
		return this.detalleVisitas;
	}

	public void setDetalleVisitas(Set<DetalleVisita> detalleVisitas) {
		this.detalleVisitas = detalleVisitas;
	}

}
