package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Bateriologo generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class Bateriologo implements java.io.Serializable {

	private Long idBate;
	private Sucursal sucursal;
	private String codigo;
	private String nombreCompleto;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;
	private Set<Garantia> garantias = new HashSet<Garantia>(0);

	public Bateriologo() {
	}

	public Bateriologo(Long idBate, Sucursal sucursal, String codigo,
			Date fechaCreacion, String operCreador, Date fechaModificacion,
			String operModifica, String estadoRegistro) {
		this.idBate = idBate;
		this.sucursal = sucursal;
		this.codigo = codigo;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public Bateriologo(Long idBate, Sucursal sucursal, String codigo,
			String nombreCompleto, Date fechaCreacion, String operCreador,
			Date fechaModificacion, String operModifica, String estadoRegistro,
			Set<Garantia> garantias) {
		this.idBate = idBate;
		this.sucursal = sucursal;
		this.codigo = codigo;
		this.nombreCompleto = nombreCompleto;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
		this.garantias = garantias;
	}

	public Long getIdBate() {
		return this.idBate;
	}

	public void setIdBate(Long idBate) {
		this.idBate = idBate;
	}

	public Sucursal getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Sucursal sucursal) {
		this.sucursal = sucursal;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getNombreCompleto() {
		return this.nombreCompleto;
	}

	public void setNombreCompleto(String nombreCompleto) {
		this.nombreCompleto = nombreCompleto;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

	public Set<Garantia> getGarantias() {
		return this.garantias;
	}

	public void setGarantias(Set<Garantia> garantias) {
		this.garantias = garantias;
	}

}
