package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ConsecutivoDocumento generated by Zathura powered by
 * Hibernate-tools(hbm2java)
 */
public class ConsecutivoDocumento implements java.io.Serializable {

	private Long idCodo;
	private Vendedor vendedor;
	private TipoDocumento tipoDocumento;
	private Sucursal sucursal;
	private Long consecutivoInicial;
	private Long consecutivoFinal;
	private Long consecutivoActual;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;
	private String codigoTerminal;
	private Set<Documento> documentos = new HashSet<Documento>(0);

	public ConsecutivoDocumento() {
	}

	public ConsecutivoDocumento(Long idCodo, Sucursal sucursal,
			Long consecutivoInicial, Long consecutivoActual,
			Date fechaCreacion, String operCreador, Date fechaModificacion,
			String operModifica, String estadoRegistro) {
		this.idCodo = idCodo;
		this.sucursal = sucursal;
		this.consecutivoInicial = consecutivoInicial;
		this.consecutivoActual = consecutivoActual;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public ConsecutivoDocumento(Long idCodo, Vendedor vendedor,
			TipoDocumento tipoDocumento, Sucursal sucursal,
			Long consecutivoInicial, Long consecutivoFinal,
			Long consecutivoActual, Date fechaCreacion, String operCreador,
			Date fechaModificacion, String operModifica, String estadoRegistro,
			String codigoTerminal, Set<Documento> documentos) {
		this.idCodo = idCodo;
		this.vendedor = vendedor;
		this.tipoDocumento = tipoDocumento;
		this.sucursal = sucursal;
		this.consecutivoInicial = consecutivoInicial;
		this.consecutivoFinal = consecutivoFinal;
		this.consecutivoActual = consecutivoActual;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
		this.codigoTerminal = codigoTerminal;
		this.documentos = documentos;
	}

	public Long getIdCodo() {
		return this.idCodo;
	}

	public void setIdCodo(Long idCodo) {
		this.idCodo = idCodo;
	}

	public Vendedor getVendedor() {
		return this.vendedor;
	}

	public void setVendedor(Vendedor vendedor) {
		this.vendedor = vendedor;
	}

	public TipoDocumento getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(TipoDocumento tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	public Sucursal getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Sucursal sucursal) {
		this.sucursal = sucursal;
	}

	public Long getConsecutivoInicial() {
		return this.consecutivoInicial;
	}

	public void setConsecutivoInicial(Long consecutivoInicial) {
		this.consecutivoInicial = consecutivoInicial;
	}

	public Long getConsecutivoFinal() {
		return this.consecutivoFinal;
	}

	public void setConsecutivoFinal(Long consecutivoFinal) {
		this.consecutivoFinal = consecutivoFinal;
	}

	public Long getConsecutivoActual() {
		return this.consecutivoActual;
	}

	public void setConsecutivoActual(Long consecutivoActual) {
		this.consecutivoActual = consecutivoActual;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

	public String getCodigoTerminal() {
		return this.codigoTerminal;
	}

	public void setCodigoTerminal(String codigoTerminal) {
		this.codigoTerminal = codigoTerminal;
	}

	public Set<Documento> getDocumentos() {
		return this.documentos;
	}

	public void setDocumentos(Set<Documento> documentos) {
		this.documentos = documentos;
	}

}
