package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * ListaPrecios generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class ListaPrecios implements java.io.Serializable {

	private Long idLipr;
	private Referencia referencia;
	private TipoLista tipoLista;
	private Sucursal sucursal;
	private Double valor;
	private Double margen;
	private Date fechaInicial;
	private Date fechaFinal;
	private String espacios;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;

	public ListaPrecios() {
	}

	public ListaPrecios(Long idLipr, Referencia referencia,
			TipoLista tipoLista, Date fechaCreacion, String operCreador,
			Date fechaModificacion, String operModifica, String estadoRegistro) {
		this.idLipr = idLipr;
		this.referencia = referencia;
		this.tipoLista = tipoLista;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public ListaPrecios(Long idLipr, Referencia referencia,
			TipoLista tipoLista, Sucursal sucursal, Double valor,
			Double margen, Date fechaInicial, Date fechaFinal, String espacios,
			Date fechaCreacion, String operCreador, Date fechaModificacion,
			String operModifica, String estadoRegistro) {
		this.idLipr = idLipr;
		this.referencia = referencia;
		this.tipoLista = tipoLista;
		this.sucursal = sucursal;
		this.valor = valor;
		this.margen = margen;
		this.fechaInicial = fechaInicial;
		this.fechaFinal = fechaFinal;
		this.espacios = espacios;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public Long getIdLipr() {
		return this.idLipr;
	}

	public void setIdLipr(Long idLipr) {
		this.idLipr = idLipr;
	}

	public Referencia getReferencia() {
		return this.referencia;
	}

	public void setReferencia(Referencia referencia) {
		this.referencia = referencia;
	}

	public TipoLista getTipoLista() {
		return this.tipoLista;
	}

	public void setTipoLista(TipoLista tipoLista) {
		this.tipoLista = tipoLista;
	}

	public Sucursal getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Sucursal sucursal) {
		this.sucursal = sucursal;
	}

	public Double getValor() {
		return this.valor;
	}

	public void setValor(Double valor) {
		this.valor = valor;
	}

	public Double getMargen() {
		return this.margen;
	}

	public void setMargen(Double margen) {
		this.margen = margen;
	}

	public Date getFechaInicial() {
		return this.fechaInicial;
	}

	public void setFechaInicial(Date fechaInicial) {
		this.fechaInicial = fechaInicial;
	}

	public Date getFechaFinal() {
		return this.fechaFinal;
	}

	public void setFechaFinal(Date fechaFinal) {
		this.fechaFinal = fechaFinal;
	}

	public String getEspacios() {
		return this.espacios;
	}

	public void setEspacios(String espacios) {
		this.espacios = espacios;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

}
