package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Referencia generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class Referencia implements java.io.Serializable {

	private Long idRefe;
	private String codigo;
	private String descripcion;
	private String descripcionCorta;
	private String unidadMedida;
	private String unidadMedidaProvisional;
	private String marca;
	private String equivalente1;
	private String equivalente2;
	private Double volumen;
	private Double galones;
	private Double porcentajeIva;
	private String pideCantidad;
	private String pideValor;
	private Double costo;
	private String aplicacion;
	private String descripcionTecnica;
	private String esGarantia;
	private Double peso;
	private Long QPorCaja;
	private Date fechaVigentePBodega;
	private Long margenMinimoPBodega;
	private Long margenMinimoGBodega;
	private Long margenMinimoRefBodega;
	private Date fechaVigentePEne;
	private Long margenMinimoPEne;
	private Long margenMinimoRefEne;
	private Long margenMinimoGEne;
	private Long productoEspecial;
	private Long productoConsumo;
	private Long manejaLote;
	private Long manejaDecimales;
	private String codigoBarras;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;
	private Set<ReferenciaSucursal> referenciaSucursals = new HashSet<ReferenciaSucursal>(
			0);
	private Set<ItemRotacion> itemRotacionsForReferenciaRecibida = new HashSet<ItemRotacion>(
			0);
	private Set<GrupoReferencia> grupoReferencias = new HashSet<GrupoReferencia>(
			0);
	private Set<ListaPrecios> listaPrecioses = new HashSet<ListaPrecios>(0);
	private Set<Pedido> pedidos = new HashSet<Pedido>(0);
	private Set<ItemLogisticaReversiva> itemLogisticaReversivas = new HashSet<ItemLogisticaReversiva>(
			0);
	private Set<OrdenesDeCompra> ordenesDeCompras = new HashSet<OrdenesDeCompra>(
			0);
	private Set<Garantia> garantias = new HashSet<Garantia>(0);
	private Set<PronosticoVenta> pronosticoVentas = new HashSet<PronosticoVenta>(
			0);
	private Set<ListaPreciosEspeciales> listaPreciosEspecialeses = new HashSet<ListaPreciosEspeciales>(
			0);
	private Set<ItemRotacion> itemRotacionsForReferenciaEntregada = new HashSet<ItemRotacion>(
			0);

	public Referencia() {
	}

	public Referencia(Long idRefe, String codigo, Date fechaCreacion,
			String operCreador, Date fechaModificacion, String operModifica,
			String estadoRegistro) {
		this.idRefe = idRefe;
		this.codigo = codigo;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public Referencia(Long idRefe, String codigo, String descripcion,
			String descripcionCorta, String unidadMedida,
			String unidadMedidaProvisional, String marca, String equivalente1,
			String equivalente2, Double volumen, Double galones,
			Double porcentajeIva, String pideCantidad, String pideValor,
			Double costo, String aplicacion, String descripcionTecnica,
			String esGarantia, Double peso, Long QPorCaja,
			Date fechaVigentePBodega, Long margenMinimoPBodega,
			Long margenMinimoGBodega, Long margenMinimoRefBodega,
			Date fechaVigentePEne, Long margenMinimoPEne,
			Long margenMinimoRefEne, Long margenMinimoGEne,
			Long productoEspecial, Long productoConsumo, Long manejaLote,
			Long manejaDecimales, String codigoBarras, Date fechaCreacion,
			String operCreador, Date fechaModificacion, String operModifica,
			String estadoRegistro, Set<ReferenciaSucursal> referenciaSucursals,
			Set<ItemRotacion> itemRotacionsForReferenciaRecibida,
			Set<GrupoReferencia> grupoReferencias,
			Set<ListaPrecios> listaPrecioses, Set<Pedido> pedidos,
			Set<ItemLogisticaReversiva> itemLogisticaReversivas,
			Set<OrdenesDeCompra> ordenesDeCompras, Set<Garantia> garantias,
			Set<PronosticoVenta> pronosticoVentas,
			Set<ListaPreciosEspeciales> listaPreciosEspecialeses,
			Set<ItemRotacion> itemRotacionsForReferenciaEntregada) {
		this.idRefe = idRefe;
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.descripcionCorta = descripcionCorta;
		this.unidadMedida = unidadMedida;
		this.unidadMedidaProvisional = unidadMedidaProvisional;
		this.marca = marca;
		this.equivalente1 = equivalente1;
		this.equivalente2 = equivalente2;
		this.volumen = volumen;
		this.galones = galones;
		this.porcentajeIva = porcentajeIva;
		this.pideCantidad = pideCantidad;
		this.pideValor = pideValor;
		this.costo = costo;
		this.aplicacion = aplicacion;
		this.descripcionTecnica = descripcionTecnica;
		this.esGarantia = esGarantia;
		this.peso = peso;
		this.QPorCaja = QPorCaja;
		this.fechaVigentePBodega = fechaVigentePBodega;
		this.margenMinimoPBodega = margenMinimoPBodega;
		this.margenMinimoGBodega = margenMinimoGBodega;
		this.margenMinimoRefBodega = margenMinimoRefBodega;
		this.fechaVigentePEne = fechaVigentePEne;
		this.margenMinimoPEne = margenMinimoPEne;
		this.margenMinimoRefEne = margenMinimoRefEne;
		this.margenMinimoGEne = margenMinimoGEne;
		this.productoEspecial = productoEspecial;
		this.productoConsumo = productoConsumo;
		this.manejaLote = manejaLote;
		this.manejaDecimales = manejaDecimales;
		this.codigoBarras = codigoBarras;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
		this.referenciaSucursals = referenciaSucursals;
		this.itemRotacionsForReferenciaRecibida = itemRotacionsForReferenciaRecibida;
		this.grupoReferencias = grupoReferencias;
		this.listaPrecioses = listaPrecioses;
		this.pedidos = pedidos;
		this.itemLogisticaReversivas = itemLogisticaReversivas;
		this.ordenesDeCompras = ordenesDeCompras;
		this.garantias = garantias;
		this.pronosticoVentas = pronosticoVentas;
		this.listaPreciosEspecialeses = listaPreciosEspecialeses;
		this.itemRotacionsForReferenciaEntregada = itemRotacionsForReferenciaEntregada;
	}

	public Long getIdRefe() {
		return this.idRefe;
	}

	public void setIdRefe(Long idRefe) {
		this.idRefe = idRefe;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getDescripcionCorta() {
		return this.descripcionCorta;
	}

	public void setDescripcionCorta(String descripcionCorta) {
		this.descripcionCorta = descripcionCorta;
	}

	public String getUnidadMedida() {
		return this.unidadMedida;
	}

	public void setUnidadMedida(String unidadMedida) {
		this.unidadMedida = unidadMedida;
	}

	public String getUnidadMedidaProvisional() {
		return this.unidadMedidaProvisional;
	}

	public void setUnidadMedidaProvisional(String unidadMedidaProvisional) {
		this.unidadMedidaProvisional = unidadMedidaProvisional;
	}

	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	public String getEquivalente1() {
		return this.equivalente1;
	}

	public void setEquivalente1(String equivalente1) {
		this.equivalente1 = equivalente1;
	}

	public String getEquivalente2() {
		return this.equivalente2;
	}

	public void setEquivalente2(String equivalente2) {
		this.equivalente2 = equivalente2;
	}

	public Double getVolumen() {
		return this.volumen;
	}

	public void setVolumen(Double volumen) {
		this.volumen = volumen;
	}

	public Double getGalones() {
		return this.galones;
	}

	public void setGalones(Double galones) {
		this.galones = galones;
	}

	public Double getPorcentajeIva() {
		return this.porcentajeIva;
	}

	public void setPorcentajeIva(Double porcentajeIva) {
		this.porcentajeIva = porcentajeIva;
	}

	public String getPideCantidad() {
		return this.pideCantidad;
	}

	public void setPideCantidad(String pideCantidad) {
		this.pideCantidad = pideCantidad;
	}

	public String getPideValor() {
		return this.pideValor;
	}

	public void setPideValor(String pideValor) {
		this.pideValor = pideValor;
	}

	public Double getCosto() {
		return this.costo;
	}

	public void setCosto(Double costo) {
		this.costo = costo;
	}

	public String getAplicacion() {
		return this.aplicacion;
	}

	public void setAplicacion(String aplicacion) {
		this.aplicacion = aplicacion;
	}

	public String getDescripcionTecnica() {
		return this.descripcionTecnica;
	}

	public void setDescripcionTecnica(String descripcionTecnica) {
		this.descripcionTecnica = descripcionTecnica;
	}

	public String getEsGarantia() {
		return this.esGarantia;
	}

	public void setEsGarantia(String esGarantia) {
		this.esGarantia = esGarantia;
	}

	public Double getPeso() {
		return this.peso;
	}

	public void setPeso(Double peso) {
		this.peso = peso;
	}

	public Long getQPorCaja() {
		return this.QPorCaja;
	}

	public void setQPorCaja(Long QPorCaja) {
		this.QPorCaja = QPorCaja;
	}

	public Date getFechaVigentePBodega() {
		return this.fechaVigentePBodega;
	}

	public void setFechaVigentePBodega(Date fechaVigentePBodega) {
		this.fechaVigentePBodega = fechaVigentePBodega;
	}

	public Long getMargenMinimoPBodega() {
		return this.margenMinimoPBodega;
	}

	public void setMargenMinimoPBodega(Long margenMinimoPBodega) {
		this.margenMinimoPBodega = margenMinimoPBodega;
	}

	public Long getMargenMinimoGBodega() {
		return this.margenMinimoGBodega;
	}

	public void setMargenMinimoGBodega(Long margenMinimoGBodega) {
		this.margenMinimoGBodega = margenMinimoGBodega;
	}

	public Long getMargenMinimoRefBodega() {
		return this.margenMinimoRefBodega;
	}

	public void setMargenMinimoRefBodega(Long margenMinimoRefBodega) {
		this.margenMinimoRefBodega = margenMinimoRefBodega;
	}

	public Date getFechaVigentePEne() {
		return this.fechaVigentePEne;
	}

	public void setFechaVigentePEne(Date fechaVigentePEne) {
		this.fechaVigentePEne = fechaVigentePEne;
	}

	public Long getMargenMinimoPEne() {
		return this.margenMinimoPEne;
	}

	public void setMargenMinimoPEne(Long margenMinimoPEne) {
		this.margenMinimoPEne = margenMinimoPEne;
	}

	public Long getMargenMinimoRefEne() {
		return this.margenMinimoRefEne;
	}

	public void setMargenMinimoRefEne(Long margenMinimoRefEne) {
		this.margenMinimoRefEne = margenMinimoRefEne;
	}

	public Long getMargenMinimoGEne() {
		return this.margenMinimoGEne;
	}

	public void setMargenMinimoGEne(Long margenMinimoGEne) {
		this.margenMinimoGEne = margenMinimoGEne;
	}

	public Long getProductoEspecial() {
		return this.productoEspecial;
	}

	public void setProductoEspecial(Long productoEspecial) {
		this.productoEspecial = productoEspecial;
	}

	public Long getProductoConsumo() {
		return this.productoConsumo;
	}

	public void setProductoConsumo(Long productoConsumo) {
		this.productoConsumo = productoConsumo;
	}

	public Long getManejaLote() {
		return this.manejaLote;
	}

	public void setManejaLote(Long manejaLote) {
		this.manejaLote = manejaLote;
	}

	public Long getManejaDecimales() {
		return this.manejaDecimales;
	}

	public void setManejaDecimales(Long manejaDecimales) {
		this.manejaDecimales = manejaDecimales;
	}

	public String getCodigoBarras() {
		return this.codigoBarras;
	}

	public void setCodigoBarras(String codigoBarras) {
		this.codigoBarras = codigoBarras;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

	public Set<ReferenciaSucursal> getReferenciaSucursals() {
		return this.referenciaSucursals;
	}

	public void setReferenciaSucursals(
			Set<ReferenciaSucursal> referenciaSucursals) {
		this.referenciaSucursals = referenciaSucursals;
	}

	public Set<ItemRotacion> getItemRotacionsForReferenciaRecibida() {
		return this.itemRotacionsForReferenciaRecibida;
	}

	public void setItemRotacionsForReferenciaRecibida(
			Set<ItemRotacion> itemRotacionsForReferenciaRecibida) {
		this.itemRotacionsForReferenciaRecibida = itemRotacionsForReferenciaRecibida;
	}

	public Set<GrupoReferencia> getGrupoReferencias() {
		return this.grupoReferencias;
	}

	public void setGrupoReferencias(Set<GrupoReferencia> grupoReferencias) {
		this.grupoReferencias = grupoReferencias;
	}

	public Set<ListaPrecios> getListaPrecioses() {
		return this.listaPrecioses;
	}

	public void setListaPrecioses(Set<ListaPrecios> listaPrecioses) {
		this.listaPrecioses = listaPrecioses;
	}

	public Set<Pedido> getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set<Pedido> pedidos) {
		this.pedidos = pedidos;
	}

	public Set<ItemLogisticaReversiva> getItemLogisticaReversivas() {
		return this.itemLogisticaReversivas;
	}

	public void setItemLogisticaReversivas(
			Set<ItemLogisticaReversiva> itemLogisticaReversivas) {
		this.itemLogisticaReversivas = itemLogisticaReversivas;
	}

	public Set<OrdenesDeCompra> getOrdenesDeCompras() {
		return this.ordenesDeCompras;
	}

	public void setOrdenesDeCompras(Set<OrdenesDeCompra> ordenesDeCompras) {
		this.ordenesDeCompras = ordenesDeCompras;
	}

	public Set<Garantia> getGarantias() {
		return this.garantias;
	}

	public void setGarantias(Set<Garantia> garantias) {
		this.garantias = garantias;
	}

	public Set<PronosticoVenta> getPronosticoVentas() {
		return this.pronosticoVentas;
	}

	public void setPronosticoVentas(Set<PronosticoVenta> pronosticoVentas) {
		this.pronosticoVentas = pronosticoVentas;
	}

	public Set<ListaPreciosEspeciales> getListaPreciosEspecialeses() {
		return this.listaPreciosEspecialeses;
	}

	public void setListaPreciosEspecialeses(
			Set<ListaPreciosEspeciales> listaPreciosEspecialeses) {
		this.listaPreciosEspecialeses = listaPreciosEspecialeses;
	}

	public Set<ItemRotacion> getItemRotacionsForReferenciaEntregada() {
		return this.itemRotacionsForReferenciaEntregada;
	}

	public void setItemRotacionsForReferenciaEntregada(
			Set<ItemRotacion> itemRotacionsForReferenciaEntregada) {
		this.itemRotacionsForReferenciaEntregada = itemRotacionsForReferenciaEntregada;
	}

}
