package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoDivision generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class TipoDivision implements java.io.Serializable {

	private Long idTidi;
	private String nombre;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;
	private Set<DivisionPolitica> divisionPoliticas = new HashSet<DivisionPolitica>(
			0);

	public TipoDivision() {
	}

	public TipoDivision(Long idTidi, String nombre, Date fechaCreacion,
			String operCreador, Date fechaModificacion, String operModifica,
			String estadoRegistro) {
		this.idTidi = idTidi;
		this.nombre = nombre;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public TipoDivision(Long idTidi, String nombre, Date fechaCreacion,
			String operCreador, Date fechaModificacion, String operModifica,
			String estadoRegistro, Set<DivisionPolitica> divisionPoliticas) {
		this.idTidi = idTidi;
		this.nombre = nombre;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
		this.divisionPoliticas = divisionPoliticas;
	}

	public Long getIdTidi() {
		return this.idTidi;
	}

	public void setIdTidi(Long idTidi) {
		this.idTidi = idTidi;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

	public Set<DivisionPolitica> getDivisionPoliticas() {
		return this.divisionPoliticas;
	}

	public void setDivisionPoliticas(Set<DivisionPolitica> divisionPoliticas) {
		this.divisionPoliticas = divisionPoliticas;
	}

}
