package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoLista generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class TipoLista implements java.io.Serializable {

	private Long idTili;
	private TipoSucursal tipoSucursal;
	private String codigo;
	private String descripcion;
	private Long esCombinacion;
	private String espacios;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;
	private Set<ListaPrecios> listaPrecioses = new HashSet<ListaPrecios>(0);

	public TipoLista() {
	}

	public TipoLista(Long idTili, TipoSucursal tipoSucursal, String codigo,
			Date fechaCreacion, String operCreador, Date fechaModificacion,
			String operModifica, String estadoRegistro) {
		this.idTili = idTili;
		this.tipoSucursal = tipoSucursal;
		this.codigo = codigo;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public TipoLista(Long idTili, TipoSucursal tipoSucursal, String codigo,
			String descripcion, Long esCombinacion, String espacios,
			Date fechaCreacion, String operCreador, Date fechaModificacion,
			String operModifica, String estadoRegistro,
			Set<ListaPrecios> listaPrecioses) {
		this.idTili = idTili;
		this.tipoSucursal = tipoSucursal;
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.esCombinacion = esCombinacion;
		this.espacios = espacios;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
		this.listaPrecioses = listaPrecioses;
	}

	public Long getIdTili() {
		return this.idTili;
	}

	public void setIdTili(Long idTili) {
		this.idTili = idTili;
	}

	public TipoSucursal getTipoSucursal() {
		return this.tipoSucursal;
	}

	public void setTipoSucursal(TipoSucursal tipoSucursal) {
		this.tipoSucursal = tipoSucursal;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Long getEsCombinacion() {
		return this.esCombinacion;
	}

	public void setEsCombinacion(Long esCombinacion) {
		this.esCombinacion = esCombinacion;
	}

	public String getEspacios() {
		return this.espacios;
	}

	public void setEspacios(String espacios) {
		this.espacios = espacios;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

	public Set<ListaPrecios> getListaPrecioses() {
		return this.listaPrecioses;
	}

	public void setListaPrecioses(Set<ListaPrecios> listaPrecioses) {
		this.listaPrecioses = listaPrecioses;
	}

}
