package co.edu.usbcali.modelo;

// Generated 21-feb-2014 23:07:19 by Zathura powered by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Vendedor generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class Vendedor implements java.io.Serializable {

	private Long idVend;
	private Persona persona;
	private Vendedor vendedor;
	private Sucursal sucursal;
	private String codigo;
	private String email;
	private Date fechaCreacion;
	private String operCreador;
	private Date fechaModificacion;
	private String operModifica;
	private String estadoRegistro;
	private Set<AtencionVendedor> atencionVendedors = new HashSet<AtencionVendedor>(
			0);
	private Set<UnidadVenta> unidadVentas = new HashSet<UnidadVenta>(0);
	private Set<Vendedor> vendedors = new HashSet<Vendedor>(0);
	private Set<ConsecutivoDocumento> consecutivoDocumentos = new HashSet<ConsecutivoDocumento>(
			0);

	public Vendedor() {
	}

	public Vendedor(Long idVend, Persona persona, Sucursal sucursal,
			String codigo, Date fechaCreacion, String operCreador,
			Date fechaModificacion, String operModifica, String estadoRegistro) {
		this.idVend = idVend;
		this.persona = persona;
		this.sucursal = sucursal;
		this.codigo = codigo;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
	}

	public Vendedor(Long idVend, Persona persona, Vendedor vendedor,
			Sucursal sucursal, String codigo, String email, Date fechaCreacion,
			String operCreador, Date fechaModificacion, String operModifica,
			String estadoRegistro, Set<AtencionVendedor> atencionVendedors,
			Set<UnidadVenta> unidadVentas, Set<Vendedor> vendedors,
			Set<ConsecutivoDocumento> consecutivoDocumentos) {
		this.idVend = idVend;
		this.persona = persona;
		this.vendedor = vendedor;
		this.sucursal = sucursal;
		this.codigo = codigo;
		this.email = email;
		this.fechaCreacion = fechaCreacion;
		this.operCreador = operCreador;
		this.fechaModificacion = fechaModificacion;
		this.operModifica = operModifica;
		this.estadoRegistro = estadoRegistro;
		this.atencionVendedors = atencionVendedors;
		this.unidadVentas = unidadVentas;
		this.vendedors = vendedors;
		this.consecutivoDocumentos = consecutivoDocumentos;
	}

	public Long getIdVend() {
		return this.idVend;
	}

	public void setIdVend(Long idVend) {
		this.idVend = idVend;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public Vendedor getVendedor() {
		return this.vendedor;
	}

	public void setVendedor(Vendedor vendedor) {
		this.vendedor = vendedor;
	}

	public Sucursal getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Sucursal sucursal) {
		this.sucursal = sucursal;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getOperCreador() {
		return this.operCreador;
	}

	public void setOperCreador(String operCreador) {
		this.operCreador = operCreador;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getOperModifica() {
		return this.operModifica;
	}

	public void setOperModifica(String operModifica) {
		this.operModifica = operModifica;
	}

	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

	public Set<AtencionVendedor> getAtencionVendedors() {
		return this.atencionVendedors;
	}

	public void setAtencionVendedors(Set<AtencionVendedor> atencionVendedors) {
		this.atencionVendedors = atencionVendedors;
	}

	public Set<UnidadVenta> getUnidadVentas() {
		return this.unidadVentas;
	}

	public void setUnidadVentas(Set<UnidadVenta> unidadVentas) {
		this.unidadVentas = unidadVentas;
	}

	public Set<Vendedor> getVendedors() {
		return this.vendedors;
	}

	public void setVendedors(Set<Vendedor> vendedors) {
		this.vendedors = vendedors;
	}

	public Set<ConsecutivoDocumento> getConsecutivoDocumentos() {
		return this.consecutivoDocumentos;
	}

	public void setConsecutivoDocumentos(
			Set<ConsecutivoDocumento> consecutivoDocumentos) {
		this.consecutivoDocumentos = consecutivoDocumentos;
	}

}
